-- hmedic:normalized v1
-- Migration 202610071454_0011_timeline. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `timeline_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `seq` INTEGER UNSIGNED NOT NULL,
    `event_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `source_type` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `summary` VARCHAR(300) NOT NULL,
    `visibility` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `structured_refs` JSON NOT NULL,
    `projection_version` SMALLINT NOT NULL,
    `source_event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `redacts_timeline_event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `redaction_reason_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_timeline_patient`(`tenant_id`, `patient_id`, `occurred_at`, `id`),
    INDEX `ix_timeline_redacts`(`tenant_id`, `redacts_timeline_event_id`),
    UNIQUE INDEX `uq_timeline_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_timeline_patient_seq`(`tenant_id`, `patient_id`, `seq`),
    UNIQUE INDEX `uq_timeline_projection`(`tenant_id`, `source_event_id`, `event_type`, `projection_version`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `projection_checkpoints` (
    `projection_name` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `last_outbox_occurred_at` DATETIME(3) NOT NULL,
    `last_event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `projection_version` SMALLINT NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`projection_name`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Timeline rows are immutable; removals append a marker in the same patient stream.
ALTER TABLE `timeline_events` ADD CONSTRAINT `chk_timeline_event_type` CHECK (event_type IN ('appointment', 'serial', 'queue_change', 'encounter_started', 'encounter_completed', 'symptom', 'diagnosis', 'prescription_finalized', 'lab_report', 'document', 'follow_up', 'communication', 'call', 'ai_approved_note', 'doctor_note', 'REDACTED'));
ALTER TABLE `timeline_events` ADD CONSTRAINT `chk_timeline_visibility` CHECK (visibility IN ('CLINICAL', 'PATIENT_SHARED', 'OPERATIONAL'));
ALTER TABLE `timeline_events` ADD CONSTRAINT `chk_timeline_seq` CHECK (seq > 0);
ALTER TABLE `timeline_events` ADD CONSTRAINT `chk_timeline_projection_version` CHECK (projection_version > 0);
ALTER TABLE `timeline_events` ADD CONSTRAINT `chk_timeline_redaction` CHECK ((event_type = 'REDACTED' AND redacts_timeline_event_id IS NOT NULL AND redaction_reason_code IS NOT NULL) OR (event_type <> 'REDACTED' AND redacts_timeline_event_id IS NULL AND redaction_reason_code IS NULL));
ALTER TABLE `timeline_events` ADD CONSTRAINT `fk_timeline_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `timeline_events` ADD CONSTRAINT `fk_timeline_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
-- The triple FK prevents a marker from hiding a different patient's entry in the same tenant.
ALTER TABLE `timeline_events` ADD UNIQUE INDEX `uq_timeline_patient_id` (`tenant_id`, `patient_id`, `id`);
ALTER TABLE `timeline_events` ADD CONSTRAINT `fk_timeline_redacts` FOREIGN KEY (`tenant_id`, `patient_id`, `redacts_timeline_event_id`) REFERENCES `timeline_events` (`tenant_id`, `patient_id`, `id`);

ALTER TABLE `projection_checkpoints` ADD CONSTRAINT `chk_projection_version` CHECK (projection_version > 0);
ALTER TABLE `projection_checkpoints` ADD CONSTRAINT `fk_projection_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
