-- hmedic:normalized v1
-- Migration 202610100359_0012_communication. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `communications` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `channel` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `purpose` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `template_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `template_version` SMALLINT NOT NULL,
    `locale` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `consent_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `business_type` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `business_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `idempotency_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `fallback_of_communication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_communications_patient`(`tenant_id`, `patient_id`, `created_at`, `id`),
    INDEX `ix_communications_status`(`tenant_id`, `status`, `created_at`),
    UNIQUE INDEX `uq_communications_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_communications_idempotency`(`tenant_id`, `idempotency_key`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `communication_attempts` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `communication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `attempt_number` SMALLINT UNSIGNED NOT NULL,
    `provider_adapter` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_message_id` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `sms_credential_scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `sms_credential_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `encoding` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `segments_estimated` SMALLINT UNSIGNED NULL,
    `outcome_class` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `possible_duplicate` BOOLEAN NOT NULL DEFAULT false,
    `sent_at` DATETIME(3) NULL,
    `delivered_at` DATETIME(3) NULL,
    `read_at` DATETIME(3) NULL,
    `failed_at` DATETIME(3) NULL,
    `provider_meta` JSON NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_communication_attempts_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_communication_attempts_number`(`tenant_id`, `communication_id`, `attempt_number`),
    UNIQUE INDEX `uq_communication_attempts_provider_message`(`provider_adapter`, `provider_message_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `communication_preferences` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `channel` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `contact_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `preference` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `consent_version` INTEGER UNSIGNED NOT NULL,
    `effective_from` DATETIME(3) NOT NULL,
    `effective_to` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_communication_preferences_patient`(`tenant_id`, `patient_id`, `channel`, `effective_from`),
    UNIQUE INDEX `uq_communication_preferences_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `communication_short_links` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `target_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `target_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `first_used_at` DATETIME(3) NULL,

    INDEX `ix_communication_short_links_expiry`(`expires_at`),
    UNIQUE INDEX `uq_communication_short_links_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_communication_short_links_token`(`token_hash`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `provider_webhook_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_adapter` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_event_id` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `received_at` DATETIME(3) NOT NULL,
    `signature_valid` BOOLEAN NOT NULL,
    `payload_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `mapped_attempt_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `payload_ref` VARCHAR(255) NULL,

    UNIQUE INDEX `uq_provider_webhook_events_event`(`provider_adapter`, `provider_event_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
ALTER TABLE `communications` ADD CONSTRAINT `fk_communications_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `communications` ADD CONSTRAINT `fk_communications_patient` FOREIGN KEY (`tenant_id`,`patient_id`) REFERENCES `patients` (`tenant_id`,`id`);
ALTER TABLE `communications` ADD CONSTRAINT `fk_communications_consent` FOREIGN KEY (`tenant_id`,`consent_id`) REFERENCES `patient_consents` (`tenant_id`,`id`);
ALTER TABLE `communications` ADD CONSTRAINT `fk_communications_fallback` FOREIGN KEY (`tenant_id`,`fallback_of_communication_id`) REFERENCES `communications` (`tenant_id`,`id`);
ALTER TABLE `communications` ADD CONSTRAINT `chk_communications_channel` CHECK (channel IN ('in_app','email','sms','whatsapp','push','phone'));
ALTER TABLE `communications` ADD CONSTRAINT `chk_communications_status` CHECK (status IN ('CREATED','CONSENT_CHECKED','QUEUED','SENDING','SENT','DELIVERED','READ','FAILED','RETRY_SCHEDULED','CANCELLED'));
ALTER TABLE `communications` ADD CONSTRAINT `chk_communications_version` CHECK (row_version > 0);

ALTER TABLE `communication_attempts` ADD CONSTRAINT `fk_communication_attempts_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `communication_attempts` ADD CONSTRAINT `fk_communication_attempts_communication` FOREIGN KEY (`tenant_id`,`communication_id`) REFERENCES `communications` (`tenant_id`,`id`);
ALTER TABLE `communication_attempts` ADD CONSTRAINT `fk_communication_attempts_credential` FOREIGN KEY (`tenant_id`,`sms_credential_id`) REFERENCES `provider_credentials` (`tenant_id`,`id`);
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_status` CHECK (status IN ('SENDING','SENT','DELIVERED','READ','FAILED','UNKNOWN'));
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_sms_credential_scope` CHECK (sms_credential_scope IS NULL OR sms_credential_scope IN ('PLATFORM','TENANT'));
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_encoding` CHECK (encoding IS NULL OR encoding IN ('text','unicode'));
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_outcome_class` CHECK (outcome_class IS NULL OR outcome_class IN ('ACCEPTED','REJECTED','PROVIDER_UNAVAILABLE','UNKNOWN_OUTCOME','RATE_LIMITED'));
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_version` CHECK (row_version > 0);
ALTER TABLE `communication_attempts` ADD CONSTRAINT `chk_communication_attempts_number` CHECK (attempt_number > 0);

ALTER TABLE `communication_preferences` ADD CONSTRAINT `fk_communication_preferences_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `communication_preferences` ADD CONSTRAINT `fk_communication_preferences_patient` FOREIGN KEY (`tenant_id`,`patient_id`) REFERENCES `patients` (`tenant_id`,`id`);
ALTER TABLE `communication_preferences` ADD CONSTRAINT `fk_communication_preferences_contact` FOREIGN KEY (`tenant_id`,`contact_id`) REFERENCES `patient_contacts` (`tenant_id`,`id`);
ALTER TABLE `communication_preferences` ADD CONSTRAINT `chk_communication_preferences_channel` CHECK (channel IN ('in_app','email','sms','whatsapp','push','phone'));
ALTER TABLE `communication_preferences` ADD CONSTRAINT `chk_communication_preferences_preference` CHECK (preference IN ('OPT_IN','OPT_OUT'));
ALTER TABLE `communication_preferences` ADD CONSTRAINT `chk_communication_preferences_version` CHECK (row_version > 0);
ALTER TABLE `communication_preferences` ADD CONSTRAINT `chk_communication_preferences_dates` CHECK (effective_to IS NULL OR effective_to >= effective_from);

ALTER TABLE `communication_short_links` ADD CONSTRAINT `fk_communication_short_links_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `communication_short_links` ADD CONSTRAINT `chk_communication_short_links_target_type` CHECK (target_type IN ('SERIAL','APPOINTMENT','PAYMENT_INTENT','PRESCRIPTION','DOCUMENT_LIST'));
ALTER TABLE `communication_short_links` ADD CONSTRAINT `chk_communication_short_links_expiry` CHECK (expires_at > created_at);

ALTER TABLE `provider_webhook_events` ADD CONSTRAINT `fk_provider_webhook_events_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `provider_webhook_events` ADD CONSTRAINT `fk_provider_webhook_events_attempt` FOREIGN KEY (`tenant_id`,`mapped_attempt_id`) REFERENCES `communication_attempts` (`tenant_id`,`id`);
ALTER TABLE `provider_webhook_events` ADD CONSTRAINT `chk_provider_webhook_events_mapping` CHECK (mapped_attempt_id IS NULL OR (tenant_id IS NOT NULL AND signature_valid = 1));
