-- hmedic:normalized v1
-- Migration 202610071550_0021_timeline_receipts. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `timeline_projection_receipts` (
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `projection_version` SMALLINT NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `processed_at` DATETIME(3) NOT NULL,
    `outcome` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_timeline_receipts_progress`(`tenant_id`, `projection_version`, `occurred_at`, `source_event_id`),
    PRIMARY KEY (`tenant_id`, `source_event_id`, `projection_version`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
ALTER TABLE `timeline_projection_receipts` ADD CONSTRAINT `chk_timeline_receipt_version` CHECK (projection_version > 0);
ALTER TABLE `timeline_projection_receipts` ADD CONSTRAINT `chk_timeline_receipt_outcome` CHECK (outcome IN ('PROJECTED', 'IGNORED'));
ALTER TABLE `timeline_projection_receipts` ADD CONSTRAINT `fk_timeline_receipt_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
