#!/usr/bin/env node
// Creates a normalized migration for one schema section (DATABASE-IMPLEMENTATION.md §1.3).
// Usage: node scripts/migration-new.mjs <nnnn>
// The SQL is generated by `prisma migrate diff` between the cumulative schema before the section and the
// cumulative schema including it (no shadow database needed), then normalized.
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { columnMeta, cumulativeSchema, readSchema, splitSections } from './lib/schema-meta.mjs';
import { normalizeMigration } from './lib/normalize.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = path.join(root, 'prisma/schema.prisma');
const migrationsDir = path.join(root, 'prisma/migrations');
const constraintsDir = path.join(root, 'sql/constraints');

const number = process.argv[2];
if (!/^\d{4}$/.test(number ?? '')) {
  console.error('usage: migration-new.mjs <nnnn>');
  process.exit(2);
}
const schema = readSchema(schemaPath);
const { sections } = splitSections(schema);
const index = sections.findIndex((s) => s.number === number);
if (index === -1) {
  console.error(`no schema section ${number}`);
  process.exit(2);
}
const existing = existsSync(migrationsDir)
  ? readdirSync(migrationsDir).filter((d) => d.includes(`_${number}_`))
  : [];
if (existing.length) {
  console.error(`migration for section ${number} already exists: ${existing.join(', ')}`);
  process.exit(2);
}
const section = sections[index];
const previous = index === 0 ? null : sections[index - 1].number;

const tmp = mkdtempSync(path.join(os.tmpdir(), 'hmedic-migration-'));
try {
  const before = path.join(tmp, 'before.prisma');
  const after = path.join(tmp, 'after.prisma');
  writeFileSync(after, cumulativeSchema(schema, number));
  const prismaCli = createRequire(import.meta.url).resolve('prisma/build/index.js');
  const args = [prismaCli, 'migrate', 'diff', '--script', '--to-schema', after];
  if (previous === null) args.push('--from-empty');
  else {
    writeFileSync(before, cumulativeSchema(schema, previous));
    args.push('--from-schema', before);
  }
  const sql = execFileSync(process.execPath, args, {
    cwd: root,
    encoding: 'utf8',
    env: { ...process.env, PRISMA_HIDE_UPDATE_MESSAGE: '1' },
  })
    .split('\n')
    .filter((l) => !l.startsWith('Loaded Prisma config'))
    .join('\n');
  const stamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12);
  const name = `${stamp}_${number}_${section.name}`;
  const { ascii } = columnMeta(schema);
  const normalized = normalizeMigration({ sql, name, ascii, constraintsDir });
  mkdirSync(path.join(migrationsDir, name), { recursive: true });
  writeFileSync(path.join(migrationsDir, name, 'migration.sql'), normalized);
  if (!existsSync(path.join(migrationsDir, 'migration_lock.toml'))) {
    writeFileSync(path.join(migrationsDir, 'migration_lock.toml'), 'provider = "mysql"\n');
  }
  console.log(`created prisma/migrations/${name}/migration.sql`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
