#!/usr/bin/env node
// `pnpm contracts:generate` writes the OpenAPI artifacts and the TypeScript path types:
//   generated/openapi.v1.json        OpenAPI 3.1.0 (TypeScript clients)
//   generated/openapi.v1.oas30.json  OpenAPI 3.0.3 (Dart client, swagger_parser)
//   generated/openapi.v1.d.ts        openapi-typescript output used by the openapi-fetch client
// `pnpm openapi:check` regenerates in memory, runs the contract lint and fails if a committed file differs.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contracts = require(path.join(root, 'dist/index.js'));
const check = process.argv.includes('--check');

const v31 = contracts.buildOpenApiV31();
const v30 = contracts.buildOpenApiV30();

// Contract lint (API-IMPLEMENTATION §1, CI-CD 10a): unique operationIds; money is never numeric.
const problems = [];
const opIds = new Set();
for (const [p, item] of Object.entries(v31.paths ?? {})) {
  for (const [method, op] of Object.entries(item)) {
    if (!op.operationId) problems.push(`${method.toUpperCase()} ${p}: missing operationId`);
    else if (opIds.has(op.operationId)) problems.push(`${op.operationId}: duplicate operationId`);
    else opIds.add(op.operationId);
  }
}
const MONEY = /(amount|fee|price|balance|total)$/i;
function walk(node, trail) {
  if (!node || typeof node !== 'object') return;
  if (node.properties) {
    for (const [name, prop] of Object.entries(node.properties)) {
      const types = [prop.type].flat();
      if (MONEY.test(name) && (types.includes('number') || types.includes('integer'))) {
        problems.push(`${trail}.${name}: money fields must be decimal strings`);
      }
    }
  }
  for (const [k, v] of Object.entries(node)) walk(v, `${trail}.${k}`);
}
walk(v31.components ?? {}, 'components');
walk(v31.paths ?? {}, 'paths');

const header = '// Generated by packages/contracts/scripts/generate.mjs from openapi.v1.json. Do not edit.\n';
const types = header + astToString(await openapiTS(v31, { alphabetize: true }));

const files = {
  'generated/openapi.v1.json': contracts.stableJson(v31),
  'generated/openapi.v1.oas30.json': contracts.stableJson(v30),
  'generated/openapi.v1.d.ts': types,
};

if (problems.length) {
  console.error(`openapi lint failed:\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

if (check) {
  const stale = Object.entries(files).filter(([rel, content]) => {
    try {
      return readFileSync(path.join(root, rel), 'utf8').replace(/\r\n/g, '\n') !== content;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(
      `openapi:check: generated files are out of date (run pnpm contracts:generate):\n  ${stale.map(([f]) => f).join('\n  ')}`,
    );
    process.exit(1);
  }
  console.log(`openapi:check: ${opIds.size} operations; artifacts up to date`);
} else {
  for (const [rel, content] of Object.entries(files)) writeFileSync(path.join(root, rel), content);
  console.log(`contracts:generate: wrote ${Object.keys(files).length} files (${opIds.size} operations)`);
}
