-- hmedic:normalized v1
-- Migration 202609221737_0007_encounters. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `encounters` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `appointment_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `covering_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `doctor_coverage_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `legacy_interim` BOOLEAN NOT NULL DEFAULT false,
    `care_mode` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `started_at` DATETIME(3) NOT NULL,
    `interrupted_at` DATETIME(3) NULL,
    `interruption_reason` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `resumed_at` DATETIME(3) NULL,
    `completed_at` DATETIME(3) NULL,
    `completion_reason` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `entered_in_error_reason` VARCHAR(300) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_encounters_patient`(`tenant_id`, `patient_id`, `started_at`),
    INDEX `ix_encounters_doctor_status`(`tenant_id`, `doctor_profile_id`, `status`),
    UNIQUE INDEX `uq_encounters_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `encounter_participants` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `participant_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `role` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `authorization_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `joined_at` DATETIME(3) NULL,
    `left_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_encounter_participants_encounter`(`tenant_id`, `encounter_id`),
    UNIQUE INDEX `uq_encounter_participants_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `encounter_notes` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `author_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chief_complaint` LONGTEXT NULL,
    `history` LONGTEXT NULL,
    `examination` LONGTEXT NULL,
    `assessment` LONGTEXT NULL,
    `plan` LONGTEXT NULL,
    `extensions` JSON NULL,
    `schema_version` SMALLINT NOT NULL DEFAULT 1,
    `section_sources` JSON NOT NULL,
    `last_signed_revision` INTEGER NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_encounter_notes_encounter`(`tenant_id`, `encounter_id`),
    UNIQUE INDEX `uq_encounter_notes_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `encounter_note_versions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `note_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `revision` INTEGER UNSIGNED NOT NULL,
    `signed_by_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `signed_at` DATETIME(3) NOT NULL,
    `chief_complaint` LONGTEXT NULL,
    `history` LONGTEXT NULL,
    `examination` LONGTEXT NULL,
    `assessment` LONGTEXT NULL,
    `plan` LONGTEXT NULL,
    `extensions` JSON NULL,
    `section_sources` JSON NOT NULL,
    `schema_version` SMALLINT NOT NULL DEFAULT 1,
    `correction_reason` VARCHAR(500) NULL,
    `supersedes_revision` INTEGER NULL,
    `content_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,

    INDEX `ix_encounter_note_versions_note`(`tenant_id`, `note_id`),
    UNIQUE INDEX `uq_encounter_note_versions_revision`(`tenant_id`, `encounter_id`, `revision`),
    UNIQUE INDEX `uq_encounter_note_versions_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `encounters` (DATABASE-IMPLEMENTATION.md §3.7). Appended by db:migration:normalize.
ALTER TABLE `encounters` ADD CONSTRAINT `chk_encounters_status` CHECK (status IN ('IN_PROGRESS', 'INTERRUPTED', 'COMPLETED', 'ENTERED_IN_ERROR'));
ALTER TABLE `encounters` ADD CONSTRAINT `chk_encounters_care_mode` CHECK (care_mode IN ('PHYSICAL', 'REMOTE', 'HYBRID'));
-- An encounter voided as entered-in-error has to say why; the row stays for the audit trail.
ALTER TABLE `encounters` ADD CONSTRAINT `chk_encounters_error_reason` CHECK (status <> 'ENTERED_IN_ERROR' OR entered_in_error_reason IS NOT NULL);
-- A covering doctor is recorded with the grant that allowed it, never one without the other.
ALTER TABLE `encounters` ADD CONSTRAINT `chk_encounters_covering_pair` CHECK ((covering_doctor_profile_id IS NULL) = (doctor_coverage_id IS NULL));
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_chamber` FOREIGN KEY (`tenant_id`, `chamber_id`) REFERENCES `chambers` (`tenant_id`, `id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_serial` FOREIGN KEY (`tenant_id`, `serial_id`) REFERENCES `serials` (`tenant_id`, `id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_appointment` FOREIGN KEY (`tenant_id`, `appointment_id`) REFERENCES `appointments` (`tenant_id`, `id`);
ALTER TABLE `encounters` ADD CONSTRAINT `fk_encounters_coverage` FOREIGN KEY (`tenant_id`, `doctor_coverage_id`) REFERENCES `doctor_coverages` (`tenant_id`, `id`);
-- One encounter per serial, enforced by the database rather than by the service that writes it. A row
-- voided as entered-in-error drops out of the key so the serial can be started again.
ALTER TABLE `encounters` ADD COLUMN `serial_encounter_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status <> 'ENTERED_IN_ERROR', serial_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_encounters_serial` ON `encounters` (`tenant_id`, `serial_encounter_key`);
-- The serial's back-pointer, added here because `serials` (0006) predates this table.
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);

-- Constraints for `encounter_participants` (DATABASE-IMPLEMENTATION.md §3.7).
ALTER TABLE `encounter_participants` ADD CONSTRAINT `chk_encounter_participants_type` CHECK (participant_type IN ('DOCTOR', 'STAFF', 'PATIENT', 'GUARDIAN', 'INTERPRETER', 'EXTERNAL'));
ALTER TABLE `encounter_participants` ADD CONSTRAINT `chk_encounter_participants_authorization` CHECK (authorization_status IN ('INVITED', 'AUTHORIZED', 'REVOKED'));
ALTER TABLE `encounter_participants` ADD CONSTRAINT `fk_encounter_participants_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `encounter_participants` ADD CONSTRAINT `fk_encounter_participants_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);

-- Constraints for `encounter_notes` (DATABASE-IMPLEMENTATION.md §3.7). The single mutable draft.
ALTER TABLE `encounter_notes` ADD CONSTRAINT `chk_encounter_notes_status` CHECK (status IN ('DRAFT', 'SIGNED_LOCKED'));
ALTER TABLE `encounter_notes` ADD CONSTRAINT `fk_encounter_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `encounter_notes` ADD CONSTRAINT `fk_encounter_notes_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
ALTER TABLE `encounter_notes` ADD CONSTRAINT `fk_encounter_notes_author` FOREIGN KEY (`tenant_id`, `author_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
-- One open draft per encounter, so two tabs cannot each create their own and silently diverge.
ALTER TABLE `encounter_notes` ADD COLUMN `open_draft_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status = 'DRAFT', encounter_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_encounter_notes_open_draft` ON `encounter_notes` (`tenant_id`, `open_draft_key`);

-- Constraints for `encounter_note_versions` (DATABASE-IMPLEMENTATION.md §3.7). Append-only, hash-chained
-- per encounter. No code path updates or deletes a row here; the repository refuses it and tests prove it.
-- A revision after the first is a correction and must carry its reason, so history explains itself.
ALTER TABLE `encounter_note_versions` ADD CONSTRAINT `chk_encounter_note_versions_correction` CHECK (revision = 1 OR correction_reason IS NOT NULL);
ALTER TABLE `encounter_note_versions` ADD CONSTRAINT `fk_encounter_note_versions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `encounter_note_versions` ADD CONSTRAINT `fk_encounter_note_versions_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
ALTER TABLE `encounter_note_versions` ADD CONSTRAINT `fk_encounter_note_versions_note` FOREIGN KEY (`tenant_id`, `note_id`) REFERENCES `encounter_notes` (`tenant_id`, `id`);
ALTER TABLE `encounter_note_versions` ADD CONSTRAINT `fk_encounter_note_versions_signer` FOREIGN KEY (`tenant_id`, `signed_by_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
