-- hmedic:normalized v1
-- Migration 202610080945_0020_follow_up. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `follow_up_plans` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `due_start_date` DATE NOT NULL,
    `due_end_date` DATE NULL,
    `reason` VARCHAR(300) NOT NULL,
    `instructions` VARCHAR(1000) NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `appointment_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_follow_up_plans_patient`(`tenant_id`, `patient_id`, `due_start_date`, `id`),
    INDEX `ix_follow_up_plans_encounter`(`tenant_id`, `source_encounter_id`),
    INDEX `ix_follow_up_plans_due`(`tenant_id`, `status`, `due_start_date`),
    UNIQUE INDEX `uq_follow_up_plans_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `follow_up_tasks` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `follow_up_plan_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `task_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `due_at` DATETIME(3) NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `assigned_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_follow_up_tasks_plan`(`tenant_id`, `follow_up_plan_id`),
    INDEX `ix_follow_up_tasks_due`(`tenant_id`, `status`, `due_at`, `id`),
    UNIQUE INDEX `uq_follow_up_tasks_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `chk_follow_up_plans_status` CHECK (status IN ('PLANNED','BOOKED','COMPLETED','CANCELLED','MISSED'));
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `chk_follow_up_plans_dates` CHECK (due_end_date IS NULL OR due_end_date >= due_start_date);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `chk_follow_up_plans_reason` CHECK (CHAR_LENGTH(TRIM(reason)) > 0);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `chk_follow_up_plans_booking` CHECK ((appointment_id IS NULL AND serial_id IS NULL AND status <> 'BOOKED') OR (appointment_id IS NOT NULL AND serial_id IS NOT NULL AND status <> 'PLANNED'));
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `chk_follow_up_plans_version` CHECK (row_version > 0);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_patient` FOREIGN KEY (`tenant_id`,`patient_id`) REFERENCES `patients` (`tenant_id`,`id`);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_encounter` FOREIGN KEY (`tenant_id`,`source_encounter_id`) REFERENCES `encounters` (`tenant_id`,`id`);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_doctor` FOREIGN KEY (`tenant_id`,`doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`,`id`);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_appointment` FOREIGN KEY (`tenant_id`,`appointment_id`) REFERENCES `appointments` (`tenant_id`,`id`);
ALTER TABLE `follow_up_plans` ADD CONSTRAINT `fk_follow_up_plans_serial` FOREIGN KEY (`tenant_id`,`serial_id`) REFERENCES `serials` (`tenant_id`,`id`);

ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `chk_follow_up_tasks_type` CHECK (task_type IN ('REMINDER','CALL','BOOKING_ASSIST'));
ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `chk_follow_up_tasks_status` CHECK (status IN ('OPEN','DONE','CANCELLED'));
ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `chk_follow_up_tasks_version` CHECK (row_version > 0);
ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `fk_follow_up_tasks_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `fk_follow_up_tasks_plan` FOREIGN KEY (`tenant_id`,`follow_up_plan_id`) REFERENCES `follow_up_plans` (`tenant_id`,`id`);
ALTER TABLE `follow_up_tasks` ADD CONSTRAINT `fk_follow_up_tasks_assignee` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`);
