-- hmedic:normalized v1
-- Migration 202609180952_0001_platform_jobs. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `singleton_locks` (
    `name` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `holder` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `lease_expires_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `jobs` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `queue` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `type` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payload` JSON NOT NULL,
    `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `priority` SMALLINT NOT NULL DEFAULT 100,
    `run_at` DATETIME(3) NOT NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `max_attempts` INTEGER NOT NULL DEFAULT 8,
    `concurrency_key` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `locked_by` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `locked_at` DATETIME(3) NULL,
    `lease_expires_at` DATETIME(3) NULL,
    `last_error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `idempotency_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `correlation_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `causation_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `finished_at` DATETIME(3) NULL,

    INDEX `ix_jobs_claim`(`queue`, `status`, `priority`, `run_at`),
    INDEX `ix_jobs_reclaim`(`status`, `lease_expires_at`),
    INDEX `ix_jobs_tenant`(`tenant_id`, `created_at`),
    INDEX `ix_jobs_concurrency`(`concurrency_key`, `status`),
    UNIQUE INDEX `uq_jobs_queue_idem`(`queue`, `idempotency_key`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `dead_letters` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `job_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `queue` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `type` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payload` JSON NOT NULL,
    `attempts` INTEGER NOT NULL,
    `last_error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `failed_at` DATETIME(3) NOT NULL,
    `replayed_at` DATETIME(3) NULL,
    `replayed_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `replay_job_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,

    UNIQUE INDEX `uq_dead_letters_job`(`job_id`),
    INDEX `ix_dead_letters_queue`(`queue`, `failed_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `job_concurrency_leases` (
    `concurrency_key` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `slot_no` SMALLINT NOT NULL,
    `job_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `lease_expires_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `uq_job_concurrency_leases_job`(`job_id`),
    PRIMARY KEY (`concurrency_key`, `slot_no`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `rate_limit_counters` (
    `scope` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `subject_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `window_start` DATETIME(3) NOT NULL,
    `window_seconds` INTEGER NOT NULL,
    `count` INTEGER UNSIGNED NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,

    INDEX `ix_rate_limit_counters_expires`(`expires_at`),
    PRIMARY KEY (`scope`, `subject_hash`, `window_start`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `jobs` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `jobs` ADD CONSTRAINT `chk_jobs_status` CHECK (status IN ('QUEUED', 'RUNNING', 'WAITING_RATE_LIMIT', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'DEAD'));
ALTER TABLE `jobs` ADD CONSTRAINT `chk_jobs_attempts` CHECK (attempts >= 0 AND max_attempts > 0);

-- Constraints for `job_concurrency_leases` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `job_concurrency_leases` ADD CONSTRAINT `chk_job_concurrency_leases_slot_no` CHECK (slot_no >= 1);

-- Constraints for `rate_limit_counters` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `rate_limit_counters` ADD CONSTRAINT `chk_rate_limit_counters_window` CHECK (window_seconds > 0);
