import type { StaffRole } from '@hmedic/kernel';
import type { TenantPermission } from './permissions';

/**
 * Role → permission map (AUTHORIZATION-MATRIX.md §1, derived from the §5 matrix; the derivation is the
 * data in `test/unit/authorization-matrix.fixture.ts`). Changing this map requires a version bump, an
 * audit row, and a passing matrix test. Permissions are necessary, never sufficient: use cases also check
 * clinic/chamber scope, assignment and patient context.
 *
 * Cells that say "if granted X" are NOT defaults here; they are membership grants.
 */
export const ROLE_PERMISSIONS_VERSION = 2;

const OWNER: readonly TenantPermission[] = [
  'tenant.manage',
  'membership.manage',
  'clinic.manage',
  'chamber.manage',
  'schedule.manage',
  'coverage.manage',
  'patient.read',
  'patient.write',
  'patient.merge',
  'patient_account.manage',
  'guardianship.manage',
  'care_team.manage',
  'appointment.read',
  'appointment.write',
  'serial.write',
  'serial.manage',
  'queue.read',
  'queue.call',
  'queue.manage',
  'chamber_day.close',
  'encounter.read',
  'encounter.manage',
  'prescription.read',
  'prescription.render',
  'prescription.void',
  'lab.write',
  'document.read',
  'document.write',
  'timeline.read',
  'followup.write',
  'communication.send',
  'communication.read',
  'communication.retry',
  'telemedicine.manage',
  'ai.policy.read',
  'ai.policy.manage',
  'ai.usage.read',
  'ai.audit.raw_read',
  'audit.read',
  'export.create',
  'payment.create',
  'payment.read',
  'payment.merchant.manage',
  'fee.manage',
  'refund.manage',
  'sms.credentials.manage',
];

const CLINIC_ADMIN: readonly TenantPermission[] = [
  'membership.manage',
  'clinic.manage',
  'chamber.manage',
  'schedule.manage',
  'coverage.manage',
  'patient.read',
  'patient.write',
  'patient.merge',
  'patient_account.manage',
  'guardianship.manage',
  'care_team.manage',
  'appointment.read',
  'appointment.write',
  'serial.write',
  'serial.manage',
  'queue.read',
  'queue.call',
  'queue.manage',
  'chamber_day.close',
  'encounter.read',
  'encounter.manage',
  'prescription.read',
  'prescription.render',
  'prescription.void',
  'lab.write',
  'document.read',
  'document.write',
  'timeline.read',
  'followup.write',
  'communication.send',
  'communication.read',
  'communication.retry',
  'telemedicine.manage',
  'ai.policy.read',
  'audit.read',
  'export.create',
  'payment.create',
  'payment.read',
  'payment.merchant.manage',
  'fee.manage',
];

const DOCTOR: readonly TenantPermission[] = [
  'patient.read',
  'patient.write',
  'patient.merge',
  'appointment.read',
  'appointment.write',
  'serial.manage',
  'queue.read',
  'queue.call',
  'queue.manage',
  'chamber_day.close',
  'encounter.read',
  'encounter.start',
  'encounter.manage',
  'encounter.complete',
  'note.write',
  'note.sign',
  'clinical.write',
  'diagnosis.write',
  'prescription.read',
  'prescription.write',
  'prescription.review',
  'prescription.approve',
  'prescription.render',
  'prescription.void',
  'lab.write',
  'lab.review',
  'document.read',
  'document.write',
  'timeline.read',
  'followup.write',
  'communication.send',
  'communication.read',
  'communication.retry',
  'telemedicine.start',
  'telemedicine.join',
  'telemedicine.manage',
  'ai.use',
  'ai.review',
  'ai.approve',
  'ai.policy.read',
  'audit.read',
  'export.create',
  'payment.read',
];

const NURSE: readonly TenantPermission[] = [
  'patient.read',
  'patient.write',
  'patient.merge',
  'appointment.read',
  'serial.manage',
  'queue.read',
  'queue.call',
  'queue.manage',
  'encounter.read',
  'encounter.start',
  'encounter.manage',
  'note.write',
  'clinical.write',
  'diagnosis.write',
  'prescription.read',
  'lab.write',
  'document.read',
  'document.write',
  'timeline.read',
  'followup.write',
  'communication.send',
  'communication.read',
  'telemedicine.join',
];

const RECEPTIONIST: readonly TenantPermission[] = [
  'patient.read',
  'patient.write',
  'patient.merge',
  'appointment.read',
  'appointment.write',
  'serial.write',
  'serial.manage',
  'queue.read',
  'queue.manage',
  'encounter.read',
  'prescription.read',
  'prescription.render',
  'lab.write',
  'document.read',
  'document.write',
  'timeline.read',
  'followup.write',
  'communication.send',
  'communication.read',
  'communication.retry',
  'payment.create',
  'payment.read',
];

const BILLING_MANAGER: readonly TenantPermission[] = [
  'patient.read',
  'appointment.read',
  'export.create',
  'payment.create',
  'payment.read',
  'fee.manage',
  'refund.manage',
];

export const ROLE_PERMISSIONS: Readonly<Record<StaffRole, readonly TenantPermission[]>> = {
  tenant_owner: OWNER,
  clinic_admin: CLINIC_ADMIN,
  doctor: DOCTOR,
  nurse: NURSE,
  receptionist: RECEPTIONIST,
  billing_manager: BILLING_MANAGER,
};

/**
 * Grants a role may never receive through `tenant_memberships.permissions` (AUTHORIZATION-MATRIX §5):
 * AI approval is doctor-only, and clinic admins cannot hand out tenant ownership or AI policy.
 */
export const NON_GRANTABLE: Readonly<Partial<Record<StaffRole, readonly TenantPermission[]>>> = {
  tenant_owner: ['ai.approve', 'note.sign', 'prescription.approve'],
  clinic_admin: ['ai.approve', 'note.sign', 'prescription.approve'],
  nurse: ['ai.approve', 'note.sign', 'prescription.approve'],
  receptionist: ['ai.approve', 'note.sign', 'prescription.approve'],
  billing_manager: ['ai.approve', 'note.sign', 'prescription.approve'],
};

/** Permissions a clinic admin may not grant to anyone (AUTHORIZATION-MATRIX §5 row 1). */
export const CLINIC_ADMIN_CANNOT_GRANT: readonly TenantPermission[] = ['tenant.manage', 'ai.policy.manage'];
