-- hmedic:normalized v1
-- Migration 202609180952_0016_sms. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `sms_balance_snapshots` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `credential_scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `credential_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `provider_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `balance` DECIMAL(12, 2) NULL,
    `currency_text` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `parse_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `checked_at` DATETIME(3) NOT NULL,

    INDEX `ix_sms_balance_snapshots_credential`(`credential_scope`, `credential_id`, `checked_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `sms_balance_snapshots` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `sms_balance_snapshots` ADD CONSTRAINT `chk_sms_balance_snapshots_scope` CHECK (credential_scope IN ('PLATFORM', 'TENANT'));
ALTER TABLE `sms_balance_snapshots` ADD CONSTRAINT `chk_sms_balance_snapshots_parse_status` CHECK (parse_status IN ('PARSED', 'UNPARSED', 'ERROR'));
ALTER TABLE `sms_balance_snapshots` ADD CONSTRAINT `chk_sms_balance_snapshots_scope_consistency` CHECK ((credential_scope = 'PLATFORM' AND credential_id IS NULL AND tenant_id IS NULL) OR (credential_scope = 'TENANT' AND credential_id IS NOT NULL AND tenant_id IS NOT NULL));
ALTER TABLE `sms_balance_snapshots` ADD CONSTRAINT `fk_sms_balance_snapshots_credential` FOREIGN KEY (`tenant_id`, `credential_id`) REFERENCES `provider_credentials` (`tenant_id`, `id`);
