import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Where the seed leaves the demo logins so they can be read again (LOCAL-DEVELOPMENT.md §3).
 *
 * The seed generates a fresh random password per user and prints it once. That is right for anything
 * shared, and wrong for a laptop: miss the scrollback and the only way back in is
 * `--rotate-passwords`, which changes every password to recover one. So in development and test the
 * passwords are also written here, under `.local/`, which `.gitignore` already excludes.
 *
 * **Refused outside development and test.** These are synthetic accounts on `example.invalid` with
 * generated passwords, and writing them to disk is a convenience whose blast radius is one developer's
 * machine. On staging or production the same file would be a credential store in the repository tree,
 * so there the passwords stay in the terminal and nowhere else.
 */
export const CREDENTIALS_FILE = '.local/dev-credentials.json';

export interface StoredCredential {
  login: string;
  role: string;
  password: string;
  /** How this account authenticates, because knowing the password is not always the point. */
  method: 'password' | 'otp';
  note?: string;
  rotatedAt: string;
}

export interface CredentialStore {
  warning: string;
  appEnv: string;
  updatedAt: string;
  credentials: StoredCredential[];
}

const WARNING =
  'Synthetic demo logins for local development only. Generated by `pnpm db:seed`. ' +
  'Never reuse these passwords anywhere real; this file is gitignored and is not a secret store.';

export function credentialsPath(root: string): string {
  return path.join(root, CREDENTIALS_FILE);
}

/** True when writing the file is appropriate for this environment. */
export function mayStore(appEnv: string): boolean {
  return appEnv === 'development' || appEnv === 'test';
}

export function readStore(root: string): CredentialStore | null {
  const file = credentialsPath(root);
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, 'utf8')) as CredentialStore;
  } catch {
    return null;
  }
}

/**
 * Merges freshly generated credentials into the store, newest winning.
 *
 * A re-run of the seed without `--rotate-passwords` creates nothing and so reports no credentials; the
 * entries already on disk are still the live ones and have to survive. Merging rather than overwriting
 * is what makes `pnpm db:seed` safe to run repeatedly without losing the way back in.
 */
export function mergeCredentials(
  existing: readonly StoredCredential[],
  fresh: readonly StoredCredential[],
): StoredCredential[] {
  const byLogin = new Map(existing.map((c) => [c.login, c]));
  for (const c of fresh) byLogin.set(c.login, c);
  return [...byLogin.values()].sort((a, b) => a.role.localeCompare(b.role) || a.login.localeCompare(b.login));
}

export function writeStore(root: string, appEnv: string, fresh: readonly StoredCredential[]): string | null {
  if (!mayStore(appEnv)) return null;
  const file = credentialsPath(root);
  mkdirSync(path.dirname(file), { recursive: true });
  const previous = readStore(root);
  const store: CredentialStore = {
    warning: WARNING,
    appEnv,
    updatedAt: new Date().toISOString(),
    credentials: mergeCredentials(previous?.credentials ?? [], fresh),
  };
  writeFileSync(file, `${JSON.stringify(store, null, 2)}\n`);
  return file;
}
