-- hmedic:normalized v1
-- Migration 202609191236_0005_scheduling. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `chambers` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `clinic_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `supports_physical` BOOLEAN NOT NULL,
    `supports_remote` BOOLEAN NOT NULL,
    `supports_hybrid` BOOLEAN NOT NULL,
    `default_queue_policy` JSON NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_payment_mode` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PAY_AT_CHAMBER',
    `telemedicine_payment_mode` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PREPAID_REQUIRED',
    `deleted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_chambers_doctor`(`tenant_id`, `doctor_profile_id`, `status`),
    INDEX `ix_chambers_clinic`(`tenant_id`, `clinic_id`),
    UNIQUE INDEX `uq_chambers_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `doctor_schedule_rules` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `rule_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `weekday` TINYINT NULL,
    `exception_date` DATE NULL,
    `local_start_time` TIME(0) NOT NULL,
    `local_end_time` TIME(0) NOT NULL,
    `capacity` SMALLINT NULL,
    `effective_from` DATE NOT NULL,
    `effective_to` DATE NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_doctor_schedule_rules_chamber`(`tenant_id`, `chamber_id`, `rule_type`, `effective_from`),
    UNIQUE INDEX `uq_doctor_schedule_rules_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `chamber_days` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `local_date` DATE NOT NULL,
    `timezone` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `local_start_time` TIME(0) NOT NULL,
    `local_end_time` TIME(0) NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `queue_policy` JSON NOT NULL,
    `next_serial_number` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `queue_order_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `expected_delay_minutes` SMALLINT NULL,
    `closed_at` DATETIME(3) NULL,
    `closed_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_chamber_days_doctor_date`(`tenant_id`, `doctor_profile_id`, `local_date`),
    UNIQUE INDEX `uq_chamber_days_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_chamber_days_date`(`tenant_id`, `chamber_id`, `local_date`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `appointment_slots` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_day_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `starts_at` DATETIME(3) NOT NULL,
    `ends_at` DATETIME(3) NOT NULL,
    `local_label` VARCHAR(40) NOT NULL,
    `capacity` SMALLINT NOT NULL,
    `booked_count` SMALLINT NOT NULL DEFAULT 0,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_appointment_slots_day`(`tenant_id`, `chamber_day_id`, `starts_at`),
    UNIQUE INDEX `uq_appointment_slots_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `appointments` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_day_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `slot_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `source` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `care_mode` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payment_requirement` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payment_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payment_hold_expires_at` DATETIME(3) NULL,
    `payment_waived_reason` VARCHAR(300) NULL,
    `payment_waived_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `cancel_reason` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `reason` VARCHAR(300) NULL,
    `rescheduled_from_appointment_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `follow_up_plan_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `booked_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `booked_on_behalf` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `deleted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_appointments_patient`(`tenant_id`, `patient_id`, `created_at`),
    INDEX `ix_appointments_day`(`tenant_id`, `doctor_profile_id`, `chamber_day_id`, `status`),
    INDEX `ix_appointments_hold`(`status`, `payment_hold_expires_at`),
    UNIQUE INDEX `uq_appointments_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `chambers` (DATABASE-IMPLEMENTATION.md §3.5). Appended by db:migration:normalize.
ALTER TABLE `chambers` ADD CONSTRAINT `chk_chambers_status` CHECK (status IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE `chambers` ADD CONSTRAINT `chk_chambers_payment_mode` CHECK (chamber_payment_mode IN ('PAY_AT_CHAMBER', 'PREPAID_REQUIRED', 'OPTIONAL_ONLINE'));
ALTER TABLE `chambers` ADD CONSTRAINT `chk_chambers_telemedicine_payment_mode` CHECK (telemedicine_payment_mode IN ('PREPAID_REQUIRED', 'OPTIONAL_ONLINE'));
ALTER TABLE `chambers` ADD CONSTRAINT `chk_chambers_modes` CHECK (supports_physical + supports_remote + supports_hybrid >= 1);
ALTER TABLE `chambers` ADD CONSTRAINT `fk_chambers_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `chambers` ADD CONSTRAINT `fk_chambers_clinic` FOREIGN KEY (`tenant_id`, `clinic_id`) REFERENCES `clinics` (`tenant_id`, `id`);
ALTER TABLE `chambers` ADD CONSTRAINT `fk_chambers_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);

-- Constraints for `doctor_schedule_rules` (DATABASE-IMPLEMENTATION.md §3.5). Appended by db:migration:normalize.
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `chk_doctor_schedule_rules_type` CHECK (rule_type IN ('WEEKLY', 'EXCEPTION_OPEN', 'EXCEPTION_CLOSED'));
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `chk_doctor_schedule_rules_times` CHECK (local_end_time > local_start_time);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `chk_doctor_schedule_rules_weekly` CHECK (rule_type <> 'WEEKLY' OR weekday IS NOT NULL);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `chk_doctor_schedule_rules_exception` CHECK (rule_type = 'WEEKLY' OR exception_date IS NOT NULL);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `chk_doctor_schedule_rules_weekday` CHECK (weekday IS NULL OR weekday BETWEEN 1 AND 7);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `fk_doctor_schedule_rules_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `fk_doctor_schedule_rules_chamber` FOREIGN KEY (`tenant_id`, `chamber_id`) REFERENCES `chambers` (`tenant_id`, `id`);
ALTER TABLE `doctor_schedule_rules` ADD CONSTRAINT `fk_doctor_schedule_rules_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);

-- Constraints for `chamber_days` (DATABASE-IMPLEMENTATION.md §3.5). Appended by db:migration:normalize.
ALTER TABLE `chamber_days` ADD CONSTRAINT `chk_chamber_days_status` CHECK (status IN ('SCHEDULED', 'OPEN', 'PAUSED', 'CLOSED', 'CANCELLED'));
ALTER TABLE `chamber_days` ADD CONSTRAINT `chk_chamber_days_times` CHECK (local_end_time > local_start_time);
ALTER TABLE `chamber_days` ADD CONSTRAINT `chk_chamber_days_closed` CHECK (status <> 'CLOSED' OR closed_at IS NOT NULL);
ALTER TABLE `chamber_days` ADD CONSTRAINT `fk_chamber_days_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `chamber_days` ADD CONSTRAINT `fk_chamber_days_chamber` FOREIGN KEY (`tenant_id`, `chamber_id`) REFERENCES `chambers` (`tenant_id`, `id`);
ALTER TABLE `chamber_days` ADD CONSTRAINT `fk_chamber_days_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);

-- Constraints for `appointment_slots` (DATABASE-IMPLEMENTATION.md §3.5). Appended by db:migration:normalize.
ALTER TABLE `appointment_slots` ADD CONSTRAINT `chk_appointment_slots_status` CHECK (status IN ('OPEN', 'FULL', 'CLOSED'));
ALTER TABLE `appointment_slots` ADD CONSTRAINT `chk_appointment_slots_times` CHECK (ends_at > starts_at);
ALTER TABLE `appointment_slots` ADD CONSTRAINT `chk_appointment_slots_booked` CHECK (booked_count <= capacity);
ALTER TABLE `appointment_slots` ADD CONSTRAINT `fk_appointment_slots_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `appointment_slots` ADD CONSTRAINT `fk_appointment_slots_day` FOREIGN KEY (`tenant_id`, `chamber_day_id`) REFERENCES `chamber_days` (`tenant_id`, `id`);

-- Constraints for `appointments` (DATABASE-IMPLEMENTATION.md §3.5). Appended by db:migration:normalize.
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_source` CHECK (source IN ('ADVANCE_BOOKING', 'WALK_IN', 'FOLLOW_UP', 'RESCHEDULE'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_care_mode` CHECK (care_mode IN ('PHYSICAL', 'REMOTE', 'HYBRID'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_status` CHECK (status IN ('REQUESTED', 'PENDING_PAYMENT', 'BOOKED', 'CANCELLED', 'RESCHEDULED', 'FULFILLED', 'NO_SHOW'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_payment_requirement` CHECK (payment_requirement IN ('NONE', 'OPTIONAL', 'PREPAID'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_payment_status` CHECK (payment_status IN ('NOT_REQUIRED', 'PENDING', 'PAID', 'WAIVED', 'REFUNDED'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_on_behalf` CHECK (booked_on_behalf IS NULL OR booked_on_behalf IN ('SELF', 'GUARDIAN', 'STAFF'));
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_hold` CHECK (status <> 'PENDING_PAYMENT' OR payment_hold_expires_at IS NOT NULL);
ALTER TABLE `appointments` ADD CONSTRAINT `chk_appointments_waived` CHECK (payment_status <> 'WAIVED' OR payment_waived_reason IS NOT NULL);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_chamber` FOREIGN KEY (`tenant_id`, `chamber_id`) REFERENCES `chambers` (`tenant_id`, `id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_day` FOREIGN KEY (`tenant_id`, `chamber_day_id`) REFERENCES `chamber_days` (`tenant_id`, `id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_slot` FOREIGN KEY (`tenant_id`, `slot_id`) REFERENCES `appointment_slots` (`tenant_id`, `id`);
ALTER TABLE `appointments` ADD CONSTRAINT `fk_appointments_rescheduled_from` FOREIGN KEY (`tenant_id`, `rescheduled_from_appointment_id`) REFERENCES `appointments` (`tenant_id`, `id`);
