-- hmedic:normalized v1
-- Migration 202610061117_0010_documents. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `documents` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `category` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `current_revision` INTEGER UNSIGNED NULL,
    `title` VARCHAR(200) NULL,
    `access_policy` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `redacted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_documents_patient`(`tenant_id`, `patient_id`, `created_at`),
    UNIQUE INDEX `uq_documents_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `document_versions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `document_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `revision` INTEGER UNSIGNED NOT NULL,
    `storage_adapter` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `storage_key` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `content_type` VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `size_bytes` BIGINT UNSIGNED NOT NULL,
    `sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `scan_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `scan_adapter` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `scan_reason` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `scanned_at` DATETIME(3) NULL,
    `derived_from_revision` INTEGER NULL,
    `uploaded_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_document_versions_key`(`storage_key`),
    INDEX `ix_document_versions_document`(`tenant_id`, `document_id`),
    UNIQUE INDEX `uq_document_versions_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_document_versions_revision`(`tenant_id`, `document_id`, `revision`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `documents` (DATABASE-IMPLEMENTATION.md §3.10, FILE-STORAGE-IMPLEMENTATION.md, ADR-016).
-- The record that a file exists, who it belongs to and who may read it. The bytes live in object storage.
ALTER TABLE `documents` ADD CONSTRAINT `chk_documents_category` CHECK (category IN ('LAB_REPORT', 'PRESCRIPTION_PDF', 'IMAGE', 'REFERRAL', 'OTHER', 'AI_RAW'));
ALTER TABLE `documents` ADD CONSTRAINT `chk_documents_status` CHECK (status IN ('CREATED', 'UPLOADING', 'UPLOADED', 'SCANNING', 'SCAN_ERROR', 'AVAILABLE', 'REJECTED', 'EXPIRED'));
ALTER TABLE `documents` ADD CONSTRAINT `chk_documents_access_policy` CHECK (access_policy IN ('CLINICAL_TEAM', 'PATIENT_SHARED', 'AUDIT_ONLY'));
-- A document that says it is available must name the revision a download would serve. Without this, an
-- AVAILABLE row with a null `current_revision` is a download that 500s instead of one that 404s.
ALTER TABLE `documents` ADD CONSTRAINT `chk_documents_available_revision` CHECK (status <> 'AVAILABLE' OR current_revision IS NOT NULL);
ALTER TABLE `documents` ADD CONSTRAINT `fk_documents_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `documents` ADD CONSTRAINT `fk_documents_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `documents` ADD CONSTRAINT `fk_documents_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);

-- Constraints for `document_versions` (DATABASE-IMPLEMENTATION.md §3.10, ADR-016 §2 and §4).
-- One stored object per revision. A correction is a new revision, never a rewrite of an old one.
ALTER TABLE `document_versions` ADD CONSTRAINT `chk_document_versions_adapter` CHECK (storage_adapter IN ('s3', 'disk'));
ALTER TABLE `document_versions` ADD CONSTRAINT `chk_document_versions_scan_status` CHECK (scan_status IN ('PENDING', 'CLEAN', 'REJECTED', 'ERROR'));
-- A verdict without the thing that reached it cannot be reviewed later, and "generated, so not scanned"
-- has to be a recorded decision rather than an empty column that looks like an oversight.
ALTER TABLE `document_versions` ADD CONSTRAINT `chk_document_versions_scan_decided` CHECK (scan_status = 'PENDING' OR (scan_adapter IS NOT NULL AND scanned_at IS NOT NULL));
-- Revisions start at 1. A zero or negative revision would sort ahead of every real one.
ALTER TABLE `document_versions` ADD CONSTRAINT `chk_document_versions_revision` CHECK (revision >= 1);
-- An empty object is not a document. Every adapter writes the bytes before the row, so a zero length
-- here means the write was lost and the row is a promise of something that is not there.
ALTER TABLE `document_versions` ADD CONSTRAINT `chk_document_versions_size` CHECK (size_bytes > 0);
ALTER TABLE `document_versions` ADD CONSTRAINT `fk_document_versions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `document_versions` ADD CONSTRAINT `fk_document_versions_document` FOREIGN KEY (`tenant_id`, `document_id`) REFERENCES `documents` (`tenant_id`, `id`);
