-- hmedic:normalized v1
-- Migration 202610102045_0013_ai_credentials. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `tenant_ai_policies` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `ai_enabled` BOOLEAN NOT NULL DEFAULT false,
    `free_tier_ai_allowed` BOOLEAN NOT NULL DEFAULT false,
    `minimization_required_for_no_training` BOOLEAN NOT NULL DEFAULT true,
    `raw_output_retention_days` SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    `allowed_provider_codes` JSON NOT NULL,
    `min_ai_consent_policy_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `policy_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `policy_text_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `decided_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `decided_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_tenant_ai_policy`(`tenant_id`),
    UNIQUE INDEX `uq_tenant_ai_policy_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `tenant_ai_policy_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `seq` INTEGER UNSIGNED NOT NULL,
    `policy_version` INTEGER UNSIGNED NOT NULL,
    `before` JSON NOT NULL,
    `after` JSON NOT NULL,
    `policy_text_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `reason` VARCHAR(500) NOT NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    UNIQUE INDEX `uq_tenant_ai_policy_event_seq`(`tenant_id`, `seq`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `ai_data_use_acknowledgements` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tier` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `terms_text_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `terms_text_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `acknowledged_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `acknowledged_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoke_reason` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_ai_ack_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_ai_ack_scope`(`tenant_id`, `doctor_profile_id`, `provider_code`, `tier`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `ai_provider_credentials` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `declared_tier` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tier_self_declared` BOOLEAN NOT NULL DEFAULT true,
    `billing_mode` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encrypted_secret` VARCHAR(2048) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `wrapped_data_key` VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `key_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `secret_last4` VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `secret_fingerprint` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `validated_at` DATETIME(3) NULL,
    `last_error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `last_error_reason` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `default_model_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `allowed_model_ids` JSON NOT NULL,
    `priority` SMALLINT NOT NULL DEFAULT 100,
    `max_concurrency` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    `quota_hint` JSON NULL,
    `data_use_ack_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoked_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_ai_credentials_status_priority`(`tenant_id`, `doctor_profile_id`, `status`, `priority`),
    UNIQUE INDEX `uq_ai_credential_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_ai_credential_doctor_id`(`tenant_id`, `doctor_profile_id`, `id`),
    UNIQUE INDEX `uq_ai_credentials`(`tenant_id`, `doctor_profile_id`, `provider_code`, `secret_fingerprint`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `ai_credential_fallbacks` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `position` SMALLINT UNSIGNED NOT NULL,
    `credential_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_ai_fallback_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_ai_fallback_position`(`tenant_id`, `doctor_profile_id`, `position`),
    UNIQUE INDEX `uq_ai_fallback_credential`(`tenant_id`, `doctor_profile_id`, `credential_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `fk_tenant_ai_policy_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `fk_tenant_ai_policy_decider` FOREIGN KEY (`decided_by_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `chk_tenant_ai_policy_retention` CHECK (raw_output_retention_days BETWEEN 0 AND 3650);
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `chk_tenant_ai_policy_versions` CHECK (row_version > 0 AND policy_version > 0 AND min_ai_consent_policy_version > 0);
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `chk_tenant_ai_policy_providers` CHECK (JSON_TYPE(allowed_provider_codes) = 'ARRAY');
ALTER TABLE `tenant_ai_policies` ADD CONSTRAINT `chk_tenant_ai_policy_decision` CHECK ((decided_at IS NULL AND decided_by_user_id IS NULL) OR (decided_at IS NOT NULL AND decided_by_user_id IS NOT NULL));

ALTER TABLE `tenant_ai_policy_events` ADD CONSTRAINT `fk_tenant_ai_event_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `tenant_ai_policy_events` ADD CONSTRAINT `fk_tenant_ai_event_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `tenant_ai_policy_events` ADD CONSTRAINT `chk_tenant_ai_event_versions` CHECK (seq > 0 AND policy_version > 0);
ALTER TABLE `tenant_ai_policy_events` ADD CONSTRAINT `chk_tenant_ai_event_snapshots` CHECK (JSON_TYPE(`before`) = 'OBJECT' AND JSON_TYPE(`after`) = 'OBJECT');

ALTER TABLE `ai_data_use_acknowledgements` ADD COLUMN `live_ack_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin AS (IF(revoked_at IS NULL, CONCAT(doctor_profile_id, ':', provider_code, ':', tier, ':', terms_text_version), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_ai_ack_live` ON `ai_data_use_acknowledgements` (`tenant_id`,`live_ack_key`);
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `fk_ai_ack_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `fk_ai_ack_doctor` FOREIGN KEY (`tenant_id`,`doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`,`id`);
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `fk_ai_ack_actor` FOREIGN KEY (`acknowledged_by_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `chk_ai_ack_tier` CHECK (tier IN ('FREE','PAID'));
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `chk_ai_ack_revocation` CHECK ((revoked_at IS NULL AND revoke_reason IS NULL) OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL AND revoke_reason IN ('TEXT_VERSION_SUPERSEDED','DOCTOR_WITHDREW','ADMIN')));
ALTER TABLE `ai_data_use_acknowledgements` ADD CONSTRAINT `chk_ai_ack_version` CHECK (row_version > 0);

ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `fk_ai_credential_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `fk_ai_credential_doctor` FOREIGN KEY (`tenant_id`,`doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`,`id`);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `fk_ai_credential_ack_scope` FOREIGN KEY (`tenant_id`,`doctor_profile_id`,`provider_code`,`declared_tier`,`data_use_ack_id`) REFERENCES `ai_data_use_acknowledgements` (`tenant_id`,`doctor_profile_id`,`provider_code`,`tier`,`id`);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `fk_ai_credential_creator` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `fk_ai_credential_revoker` FOREIGN KEY (`revoked_by_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_tier` CHECK (declared_tier IN ('FREE','PAID'));
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_billing` CHECK ((billing_mode = 'DOCTOR_BYOK_FREE' AND declared_tier = 'FREE') OR (billing_mode = 'DOCTOR_BYOK_PAID' AND declared_tier = 'PAID') OR billing_mode = 'PLATFORM_MANAGED');
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_status` CHECK (status IN ('PENDING_VALIDATION','ACTIVE','INVALID','QUOTA_EXHAUSTED','DISABLED','REVOKED'));
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_concurrency` CHECK (max_concurrency BETWEEN 1 AND 4);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_models` CHECK (JSON_TYPE(allowed_model_ids) = 'ARRAY');
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_version` CHECK (row_version > 0);
ALTER TABLE `ai_provider_credentials` ADD CONSTRAINT `chk_ai_credential_revocation` CHECK ((status = 'REVOKED' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL AND encrypted_secret = 'revoked' AND wrapped_data_key = 'revoked' AND secret_fingerprint = CONCAT('rev_',REPLACE(id,'-',''))) OR (status <> 'REVOKED' AND revoked_at IS NULL AND revoked_by_user_id IS NULL));

ALTER TABLE `ai_credential_fallbacks` ADD CONSTRAINT `fk_ai_fallback_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `ai_credential_fallbacks` ADD CONSTRAINT `fk_ai_fallback_doctor` FOREIGN KEY (`tenant_id`,`doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`,`id`);
ALTER TABLE `ai_credential_fallbacks` ADD CONSTRAINT `fk_ai_fallback_credential_scope` FOREIGN KEY (`tenant_id`,`doctor_profile_id`,`credential_id`) REFERENCES `ai_provider_credentials` (`tenant_id`,`doctor_profile_id`,`id`);
ALTER TABLE `ai_credential_fallbacks` ADD CONSTRAINT `chk_ai_fallback_position` CHECK (position > 0 AND row_version > 0);
