-- hmedic:normalized v1
-- Migration 202609180952_0003_auth_sessions. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `sessions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `client_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `device_label` VARCHAR(80) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `last_seen_at` DATETIME(3) NOT NULL,
    `idle_expires_at` DATETIME(3) NOT NULL,
    `absolute_expires_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoke_reason` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `authn_methods` JSON NOT NULL,
    `ip_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,

    INDEX `ix_sessions_user`(`user_id`, `revoked_at`),
    INDEX `ix_sessions_expiry`(`absolute_expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `refresh_tokens` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `session_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `family_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `issued_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `used_at` DATETIME(3) NULL,
    `replaced_by_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `revoked_at` DATETIME(3) NULL,

    UNIQUE INDEX `uq_refresh_tokens_hash`(`token_hash`),
    INDEX `ix_refresh_tokens_family`(`family_id`),
    INDEX `ix_refresh_tokens_session`(`session_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `otp_challenges` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `purpose` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `destination_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `channel` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `code_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `attempts` SMALLINT NOT NULL DEFAULT 0,
    `max_attempts` SMALLINT NOT NULL DEFAULT 5,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `consumed_at` DATETIME(3) NULL,
    `ip_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,

    INDEX `ix_otp_challenges_expires`(`expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `password_reset_tokens` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `used_at` DATETIME(3) NULL,
    `ip_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,

    UNIQUE INDEX `uq_password_reset_tokens_hash`(`token_hash`),
    INDEX `ix_password_reset_tokens_expires`(`expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `email_verification_tokens` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `email_normalized` VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `used_at` DATETIME(3) NULL,

    UNIQUE INDEX `uq_email_verification_tokens_hash`(`token_hash`),
    INDEX `ix_email_verification_tokens_expires`(`expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `push_devices` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `session_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `platform` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `app` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_encrypted` VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `last_seen_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,

    INDEX `ix_push_devices_user`(`user_id`, `revoked_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `sessions` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `sessions` ADD CONSTRAINT `chk_sessions_client_type` CHECK (client_type IN ('WEB', 'ANDROID', 'IOS'));
ALTER TABLE `sessions` ADD CONSTRAINT `chk_sessions_revoke_reason` CHECK (revoke_reason IS NULL OR revoke_reason IN ('LOGOUT', 'LOGOUT_ALL', 'REFRESH_REUSE', 'ADMIN', 'PASSWORD_CHANGED', 'EXPIRED'));
ALTER TABLE `sessions` ADD CONSTRAINT `fk_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `refresh_tokens` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `refresh_tokens` ADD CONSTRAINT `fk_refresh_tokens_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE;

-- Constraints for `otp_challenges` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `otp_challenges` ADD CONSTRAINT `chk_otp_challenges_purpose` CHECK (purpose IN ('LOGIN', 'PHONE_VERIFY', 'RECOVERY'));
ALTER TABLE `otp_challenges` ADD CONSTRAINT `chk_otp_challenges_channel` CHECK (channel IN ('SMS', 'WHATSAPP', 'MOCK'));
ALTER TABLE `otp_challenges` ADD CONSTRAINT `chk_otp_challenges_status` CHECK (status IN ('PENDING', 'VERIFIED', 'EXPIRED', 'LOCKED', 'SUPERSEDED'));
ALTER TABLE `otp_challenges` ADD CONSTRAINT `chk_otp_challenges_attempts` CHECK (attempts >= 0 AND max_attempts > 0);
ALTER TABLE `otp_challenges` ADD COLUMN `pending_key` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status = 'PENDING', CONCAT(purpose, ':', destination_hash), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_otp_pending` ON `otp_challenges` (`pending_key`);

-- Constraints for `password_reset_tokens` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `password_reset_tokens` ADD CONSTRAINT `fk_password_reset_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `email_verification_tokens` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `email_verification_tokens` ADD CONSTRAINT `fk_email_verification_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `push_devices` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `push_devices` ADD CONSTRAINT `chk_push_devices_platform` CHECK (platform IN ('ANDROID', 'IOS', 'WEB'));
ALTER TABLE `push_devices` ADD CONSTRAINT `chk_push_devices_app` CHECK (app IN ('DOCTOR_APP', 'PATIENT_APP', 'WEB'));
ALTER TABLE `push_devices` ADD CONSTRAINT `fk_push_devices_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `push_devices` ADD COLUMN `active_token_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin AS (IF(revoked_at IS NULL, token_hash, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_push_active_token` ON `push_devices` (`active_token_key`);
