-- hmedic:normalized v1
-- Migration 202609180952_0015_platform_credentials. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `platform_operators` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `permissions` JSON NOT NULL,
    `granted_by` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `granted_at` DATETIME(3) NOT NULL,
    `revoked_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_platform_operators_user`(`user_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `platform_gate_decisions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `seq` BIGINT UNSIGNED NOT NULL,
    `gate_code` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `environment` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `decision` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `owner_name` VARCHAR(120) NOT NULL,
    `evidence_ref` VARCHAR(500) NOT NULL,
    `notes` VARCHAR(1000) NULL,
    `decided_by` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `decided_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    UNIQUE INDEX `uq_platform_gate_decisions_seq`(`seq`),
    INDEX `ix_platform_gate_decisions_gate`(`gate_code`, `environment`, `seq`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `provider_credentials` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `owner_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `clinic_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `provider_kind` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `environment` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `public_identifier` VARCHAR(64) NULL,
    `encrypted_secret` VARCHAR(4096) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `wrapped_data_key` VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `key_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `secret_last4` VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `identifier_last4` VARCHAR(4) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `secret_fingerprint` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `sender_id_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `balance_alert_bdt` DECIMAL(12, 2) NULL,
    `validated_at` DATETIME(3) NULL,
    `last_error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `revoked_at` DATETIME(3) NULL,
    `revoked_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_provider_credentials_kind`(`tenant_id`, `provider_kind`, `status`),
    UNIQUE INDEX `uq_provider_credentials_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `platform_operators` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `platform_operators` ADD CONSTRAINT `chk_platform_operators_status` CHECK (status IN ('ACTIVE', 'SUSPENDED', 'REVOKED'));
ALTER TABLE `platform_operators` ADD CONSTRAINT `fk_platform_operators_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `platform_gate_decisions` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `platform_gate_decisions` ADD CONSTRAINT `chk_platform_gate_decisions_gate_code` CHECK (gate_code IN ('GATE-SMS-HTTP', 'GATE-PAY-PLATFORM-COLLECTION'));
ALTER TABLE `platform_gate_decisions` ADD CONSTRAINT `chk_platform_gate_decisions_environment` CHECK (environment IN ('staging', 'production'));
ALTER TABLE `platform_gate_decisions` ADD CONSTRAINT `chk_platform_gate_decisions_decision` CHECK (decision IN ('ACCEPTED', 'REVOKED'));
ALTER TABLE `platform_gate_decisions` ADD CONSTRAINT `chk_platform_gate_decisions_expiry` CHECK (decision <> 'ACCEPTED' OR expires_at IS NOT NULL);

-- Constraints for `provider_credentials` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_owner_type` CHECK (owner_type IN ('TENANT', 'CLINIC', 'DOCTOR'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_provider_kind` CHECK (provider_kind IN ('SMS', 'PAYMENT'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_environment` CHECK (environment IN ('sandbox', 'live', 'na'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_status` CHECK (status IN ('PENDING_VALIDATION', 'ACTIVE', 'UNVERIFIED_UNTIL_FIRST_PAYMENT', 'INVALID', 'SUSPENDED_BALANCE', 'DISABLED', 'REVOKED'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_sender_id_status` CHECK (sender_id_status IS NULL OR sender_id_status IN ('UNVERIFIED', 'VERIFIED', 'INVALID'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_doctor_owner` CHECK (owner_type <> 'DOCTOR' OR doctor_profile_id IS NOT NULL);
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_clinic_owner` CHECK (owner_type <> 'CLINIC' OR clinic_id IS NOT NULL);
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_sms_env` CHECK (provider_kind <> 'SMS' OR environment = 'na');
ALTER TABLE `provider_credentials` ADD CONSTRAINT `chk_provider_credentials_payment_env` CHECK (provider_kind <> 'PAYMENT' OR environment IN ('sandbox', 'live'));
ALTER TABLE `provider_credentials` ADD CONSTRAINT `fk_provider_credentials_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `provider_credentials` ADD CONSTRAINT `fk_provider_credentials_clinic` FOREIGN KEY (`tenant_id`, `clinic_id`) REFERENCES `clinics` (`tenant_id`, `id`);
ALTER TABLE `provider_credentials` ADD CONSTRAINT `fk_provider_credentials_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `provider_credentials` ADD COLUMN `live_credential_key` VARCHAR(140) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status <> 'REVOKED', CONCAT(provider_kind, ':', provider_code, ':', environment, ':', secret_fingerprint), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_provider_credentials_live` ON `provider_credentials` (`tenant_id`, `live_credential_key`);
