// AUTHORIZATION-MATRIX.md §5 as data (generated once from the doc; the matrix test re-parses the doc and
// requires equality, so any doc change must be mirrored here together with the expectations below).
export const MATRIX_COLUMNS = [
  'tenant_owner',
  'clinic_admin',
  'doctor',
  'nurse',
  'receptionist',
  'billing_manager',
  'patient_context',
] as const;

export const MATRIX_ROWS: ReadonlyArray<{ resource: string; cells: readonly string[] }> = [
  {
    resource: 'Tenant settings, memberships',
    cells: [
      'M',
      'M (own clinics; cannot grant `tenant.manage`/`ai.policy.manage`)',
      'R own membership',
      'R own',
      'R own',
      'R own',
      '-',
    ],
  },
  {
    resource: 'Clinics, chambers, schedules',
    cells: [
      'CRUD/M',
      'CRUD/M (scope)',
      'R; U own schedule rules if granted',
      'R',
      'R',
      '-',
      'R public chamber info',
    ],
  },
  {
    resource: 'Patients (demographics)',
    cells: [
      'CRUD/M/E',
      'CRUD/M (scope)',
      'R/U (asg)',
      'R/U limited (scope)',
      'C/R/U demographics (scope)',
      'R billing identity',
      'R/U own limited (own, g:VIEW_RECORDS)',
    ],
  },
  {
    resource: 'Patient merge cases',
    cells: ['C/R/A', 'C/R/A (scope)', 'C/R (asg)', 'C', 'C', '-', '-'],
  },
  {
    resource: 'Patient accounts / guardianships',
    cells: [
      'M',
      'M (scope)',
      'R (asg)',
      'R (scope)',
      'C/R/verify if granted `patient_account.manage`/`guardianship.manage`',
      '-',
      'C request (PENDING) own/dependents; R own',
    ],
  },
  {
    resource: 'Care team / coverage',
    cells: ['M', 'M (scope)', 'R; M own coverage if `coverage.manage`', 'R', '-', '-', '-'],
  },
  {
    resource: 'Appointments',
    cells: [
      'CRUD/M/E',
      'CRUD/M (scope)',
      'R/U (asg chambers)',
      'R (scope)',
      'C/R/U/V (scope)',
      'R billing fields',
      'C/R/V own (own, g:BOOK_APPOINTMENTS)',
    ],
  },
  {
    resource: 'Serials (issue, check-in, cancel, reschedule, no-show)',
    cells: [
      'CRUD/M',
      'CRUD/M (scope)',
      'R/M (own chambers)',
      'R/M per policy (scope)',
      'C/R/M (scope)',
      '-',
      'R own status + estimated position; check-in/remote-ready own (g:MANAGE_SERIALS)',
    ],
  },
  {
    resource: 'Queue (call, skip, recall, reorder, delay, close day)',
    cells: [
      'M/E',
      'M (scope)',
      'M call/skip/recall/reorder (own chambers); close day',
      'M per chamber policy',
      'M per chamber policy (no call by default)',
      '-',
      'R own position only',
    ],
  },
  {
    resource: 'Encounters (start, interrupt, complete)',
    cells: [
      'R/M/E',
      'R/M (scope)',
      'C/R/U/complete (asg)',
      'C/R/U permitted sections (scope)',
      'R status only',
      '-',
      'R shared summary (own, g:VIEW_RECORDS)',
    ],
  },
  {
    resource: 'Encounter notes (draft, sign, correct)',
    cells: [
      'R/E',
      'R (scope)',
      'C/R/U/A sign (asg)',
      'C/R/U draft permitted sections (scope); no sign',
      '-',
      '-',
      'R signed only',
    ],
  },
  {
    resource: 'Diagnoses',
    cells: ['R/E', 'R (scope)', 'C/R/U (asg)', 'C/R observed/proposed (scope)', '-', '-', 'R approved'],
  },
  {
    resource: 'Prescriptions',
    cells: [
      'R/E/V (with reason)',
      'R/V (scope, with reason)',
      'C/R/U/review/A/V (asg)',
      'R; review if granted `prescription.review`; no A',
      'R status only',
      '-',
      'R approved (own, g:VIEW_RECORDS)',
    ],
  },
  {
    resource: 'Prescription render',
    cells: ['M', 'M (scope)', 'M (asg)', '-', 'M re-render approved (scope)', '-', '-'],
  },
  {
    resource: 'Labs',
    cells: [
      'CRUD/M/E',
      'CRUD/M/E (scope)',
      'C/R/U/review (asg)',
      'C/R/U (scope)',
      'C/R metadata (scope)',
      '-',
      'C/R own (own, g:UPLOAD_DOCUMENTS/VIEW_RECORDS)',
    ],
  },
  {
    resource: 'Documents',
    cells: [
      'CRUD/M/E',
      'CRUD/M/E (scope)',
      'C/R/U (asg)',
      'C/R (scope)',
      'C/R upload metadata (scope)',
      '-',
      'C/R own/shared',
    ],
  },
  {
    resource: 'Timeline',
    cells: [
      'R/E',
      'R/E (scope)',
      'R (asg)/E',
      'R (scope)',
      'R operational subset (scope)',
      '-',
      'R own approved/shared',
    ],
  },
  {
    resource: 'Follow-ups',
    cells: [
      'CRUD/M/E',
      'CRUD/M (scope)',
      'C/R/U (asg)',
      'C/R task support (scope)',
      'C/R scheduling (scope)',
      '-',
      'C/R own actions',
    ],
  },
  {
    resource: 'Communications',
    cells: [
      'CRUD/M/E',
      'CRUD/M (scope)',
      'C/R/M (asg)',
      'C/R (scope)',
      'C/R/M operational (scope)',
      '-',
      'R own; M own preferences (g:MANAGE_COMMUNICATION_PREFERENCES)',
    ],
  },
  {
    resource: 'Telemedicine',
    cells: [
      'M/E',
      'M/E (scope)',
      'C/R/M (asg)',
      'R/join (scope)',
      'R readiness (scope)',
      '-',
      'join own (g:JOIN_TELEMEDICINE)',
    ],
  },
  {
    resource: 'AI use/review/approve',
    cells: [
      '- by default (grantable `ai.use`/`ai.review` only; never `ai.approve`)',
      '-',
      'use/review/A (asg; own credentials only)',
      'review only if granted `ai.review`; never A',
      '-',
      '-',
      '-',
    ],
  },
  {
    resource: 'AI credentials (own)',
    cells: ['-', '-', 'C/R metadata/U/V (own)', '-', '-', '-', '-'],
  },
  {
    resource: "AI credentials (others')",
    cells: [
      'M if granted `ai.credentials.manage` (no secret read)',
      'M if granted `ai.credentials.manage` (no secret read)',
      '-',
      '-',
      '-',
      '-',
      '-',
    ],
  },
  {
    resource: 'AI data-use acknowledgement',
    cells: ['-', '-', 'C (self only)', '-', '-', '-', '-'],
  },
  {
    resource: 'Tenant AI policy',
    cells: ['R/M (`ai.policy.manage`)', 'R', 'R', '-', '-', '-', '-'],
  },
  {
    resource: 'AI usage',
    cells: ['R (`ai.usage.read`)', 'R if granted', 'R (own)', '-', '-', '-', '-'],
  },
  {
    resource: 'AI raw outputs',
    cells: ['R (`ai.audit.raw_read`, audited)', '-', '-', '-', '-', '-', '-'],
  },
  {
    resource: 'Audit',
    cells: [
      'R/E/M policy',
      'R/E (scope)',
      'R access to own assigned patients',
      '-',
      '-',
      '-',
      'R own access log where allowed',
    ],
  },
  {
    resource: 'Payment intents (Stage 3.2)',
    cells: [
      'C/R/E',
      'C/R (scope)',
      'R (own chambers); C if granted `payment.create`',
      '-',
      'C/R (scope; staff-assisted)',
      'C/R/E',
      'C/R own (own, g:MAKE_PAYMENTS)',
    ],
  },
  {
    resource: 'Payment review (late/mismatch)',
    cells: [
      'M (doctor-merchant intents)',
      'M (scope, if granted `payment.merchant.manage`)',
      'M own doctor-owned merchant intents',
      '-',
      '-',
      'M if granted `payment.merchant.manage`',
      '-',
    ],
  },
  {
    resource: 'Fee schedules',
    cells: [
      'M',
      'M (scope)',
      'R; U own `DOCTOR` scope if granted `fee.manage`',
      'R',
      'R',
      'M',
      'R applicable fee during booking',
    ],
  },
  {
    resource: 'Merchant accounts, payment settings',
    cells: [
      'M clinic-owned + platform opt-in; V doctor-owned (no secret read)',
      'M clinic-owned (scope)',
      'M own doctor-owned (no secret read after submit)',
      '-',
      '-',
      'R metadata',
      '-',
    ],
  },
  {
    resource: 'Refunds (`DOCTOR_MERCHANT`)',
    cells: [
      'M',
      'M (scope) if granted `refund.manage`',
      'M own doctor-owned merchant intents',
      '-',
      '-',
      'M',
      'R own refund status',
    ],
  },
  {
    resource: 'SMS credentials',
    cells: ['M', 'M if granted `sms.credentials.manage`', '-', '-', '-', '-', '-'],
  },
  {
    resource: 'Subscription and invoices',
    cells: ['R; C pay (`payment.create` + `tenant.manage`)', 'R', '-', '-', '-', 'R', '-'],
  },
];
