-- hmedic:normalized v1
-- Migration 202609230524_0008_clinical_observations. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `symptom_observations` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `normalized_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `code_system` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `display` VARCHAR(200) NOT NULL,
    `detail` VARCHAR(1000) NULL,
    `onset` VARCHAR(80) NULL,
    `severity` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `source` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `certainty` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_symptom_observations_encounter`(`tenant_id`, `encounter_id`),
    INDEX `ix_symptom_observations_patient`(`tenant_id`, `patient_id`, `created_at`),
    UNIQUE INDEX `uq_symptom_observations_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `diagnoses` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `author_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `code_system` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `display` VARCHAR(300) NOT NULL,
    `display_bn` VARCHAR(300) NULL,
    `clinical_status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `certainty` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `notes` VARCHAR(1000) NULL,
    `void_reason` VARCHAR(500) NULL,
    `voided_at` DATETIME(3) NULL,
    `voided_by_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `replaces_diagnosis_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_diagnoses_encounter`(`tenant_id`, `encounter_id`),
    INDEX `ix_diagnoses_patient`(`tenant_id`, `patient_id`, `created_at`),
    UNIQUE INDEX `uq_diagnoses_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `symptom_observations` (DATABASE-IMPLEMENTATION.md §3.8). Appended by db:migration:normalize.
ALTER TABLE `symptom_observations` ADD CONSTRAINT `chk_symptom_observations_severity` CHECK (severity IS NULL OR severity IN ('MILD', 'MODERATE', 'SEVERE', 'UNKNOWN'));
ALTER TABLE `symptom_observations` ADD CONSTRAINT `chk_symptom_observations_source` CHECK (source IN ('PATIENT_REPORTED', 'CLINICIAN_OBSERVED', 'AI_APPROVED'));
ALTER TABLE `symptom_observations` ADD CONSTRAINT `chk_symptom_observations_certainty` CHECK (certainty IN ('CONFIRMED', 'PROVISIONAL', 'DIFFERENTIAL'));
ALTER TABLE `symptom_observations` ADD CONSTRAINT `chk_symptom_observations_status` CHECK (status IN ('ACTIVE', 'ENTERED_IN_ERROR'));
-- A code without the system that issued it says nothing, and a system without a code is an empty label.
ALTER TABLE `symptom_observations` ADD CONSTRAINT `chk_symptom_observations_coding` CHECK ((normalized_code IS NULL) = (code_system IS NULL));
ALTER TABLE `symptom_observations` ADD CONSTRAINT `fk_symptom_observations_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `symptom_observations` ADD CONSTRAINT `fk_symptom_observations_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
ALTER TABLE `symptom_observations` ADD CONSTRAINT `fk_symptom_observations_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);

-- Constraints for `diagnoses` (DATABASE-IMPLEMENTATION.md §3.8). Appended by db:migration:normalize.
ALTER TABLE `diagnoses` ADD CONSTRAINT `chk_diagnoses_clinical_status` CHECK (clinical_status IN ('ACTIVE', 'RESOLVED', 'RULED_OUT', 'ENTERED_IN_ERROR'));
ALTER TABLE `diagnoses` ADD CONSTRAINT `chk_diagnoses_certainty` CHECK (certainty IN ('CONFIRMED', 'PROVISIONAL', 'DIFFERENTIAL'));
-- `ai_approved` is reachable only from Stage 10, which adds `ai_approval_id` and the CHECK that pairs
-- them (0013). Until then the value exists in the domain and nothing can write it.
ALTER TABLE `diagnoses` ADD CONSTRAINT `chk_diagnoses_source` CHECK (source IN ('doctor', 'ai_approved'));
-- A code without the system that issued it says nothing, and a system without a code is an empty label.
ALTER TABLE `diagnoses` ADD CONSTRAINT `chk_diagnoses_coding` CHECK ((code IS NULL) = (code_system IS NULL));
-- Voiding is the only way a signed diagnosis changes, so a voided row carries who did it, when and why,
-- and a row that is not voided carries none of those.
ALTER TABLE `diagnoses` ADD CONSTRAINT `chk_diagnoses_void` CHECK ((clinical_status = 'ENTERED_IN_ERROR') = (void_reason IS NOT NULL AND voided_at IS NOT NULL AND voided_by_doctor_profile_id IS NOT NULL));
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_author` FOREIGN KEY (`tenant_id`, `author_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_voided_by` FOREIGN KEY (`tenant_id`, `voided_by_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `diagnoses` ADD CONSTRAINT `fk_diagnoses_replaces` FOREIGN KEY (`tenant_id`, `replaces_diagnosis_id`) REFERENCES `diagnoses` (`tenant_id`, `id`);
