-- hmedic:normalized v1
-- Migration 202609190948_0004_patient_identity. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `patients` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `medical_record_number` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `legal_name` VARCHAR(200) NOT NULL,
    `legal_name_bn` VARCHAR(200) NULL,
    `display_name` VARCHAR(120) NOT NULL,
    `date_of_birth` DATE NULL,
    `birth_year` SMALLINT NULL,
    `sex` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `gender_identity` VARCHAR(60) NULL,
    `address` JSON NULL,
    `preferred_locale` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `merged_into_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patients_legal_name`(`tenant_id`, `legal_name`),
    INDEX `ix_patients_status_created`(`tenant_id`, `status`, `created_at`),
    UNIQUE INDEX `uq_patients_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_patients_mrn`(`tenant_id`, `medical_record_number`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_search_tokens` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token_kind` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `token` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `translit_version` SMALLINT NOT NULL,
    `created_at` DATETIME(3) NOT NULL,

    INDEX `ix_patient_search_tokens_token`(`tenant_id`, `token`, `patient_id`),
    UNIQUE INDEX `uq_patient_search_tokens`(`tenant_id`, `patient_id`, `token_kind`, `token`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_contacts` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `normalized_value` VARCHAR(254) NOT NULL,
    `normalized_value_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `display_value` VARCHAR(254) NOT NULL,
    `verification_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verified_at` DATETIME(3) NULL,
    `is_preferred` BOOLEAN NOT NULL DEFAULT false,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `relationship` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_contacts_lookup`(`tenant_id`, `type`, `normalized_value_hash`),
    INDEX `ix_patient_contacts_patient`(`tenant_id`, `patient_id`),
    UNIQUE INDEX `uq_patient_contacts_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_identifiers` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `identifier_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `identifier_value_encrypted` VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `identifier_value_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verification_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verified_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_identifiers_lookup`(`tenant_id`, `identifier_type`, `identifier_value_hash`),
    INDEX `ix_patient_identifiers_patient`(`tenant_id`, `patient_id`),
    UNIQUE INDEX `uq_patient_identifiers_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_consents` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `purpose` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `policy_version` INTEGER NOT NULL,
    `given_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `given_by_relationship` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `evidence_ref` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `captured_at` DATETIME(3) NOT NULL,
    `withdrawn_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_consents_purpose`(`tenant_id`, `patient_id`, `purpose`, `status`),
    UNIQUE INDEX `uq_patient_consents_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_merge_cases` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `target_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `reason` VARCHAR(500) NOT NULL,
    `duplicate_score` DECIMAL(5, 4) NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `requested_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `reviewed_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `reviewed_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_merge_cases_status`(`tenant_id`, `status`, `created_at`),
    UNIQUE INDEX `uq_patient_merge_cases_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_accounts` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `relationship` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verification_method` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verified_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `verified_at` DATETIME(3) NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_accounts_user`(`user_id`, `status`),
    INDEX `ix_patient_accounts_patient`(`tenant_id`, `patient_id`),
    UNIQUE INDEX `uq_patient_accounts_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_guardianships` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `guardian_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `guardian_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `dependent_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `relationship` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `authority_scope` JSON NOT NULL,
    `verification_method` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `verified_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `verified_at` DATETIME(3) NULL,
    `evidence_ref` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `starts_on` DATE NOT NULL,
    `ends_on` DATE NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_patient_guardianships_guardian`(`guardian_user_id`, `status`),
    INDEX `ix_patient_guardianships_dependent`(`tenant_id`, `dependent_patient_id`),
    UNIQUE INDEX `uq_patient_guardianships_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `care_team_members` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `member_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `role` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `starts_at` DATETIME(3) NOT NULL,
    `ends_at` DATETIME(3) NULL,
    `reason` VARCHAR(300) NULL,
    `added_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_care_team_members_member`(`tenant_id`, `member_user_id`, `ends_at`),
    INDEX `ix_care_team_members_patient`(`tenant_id`, `patient_id`),
    UNIQUE INDEX `uq_care_team_members_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `patients` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patients` ADD CONSTRAINT `chk_patients_sex` CHECK (sex IS NULL OR sex IN ('FEMALE', 'MALE', 'INTERSEX', 'UNKNOWN'));
ALTER TABLE `patients` ADD CONSTRAINT `chk_patients_status` CHECK (status IN ('ACTIVE', 'MERGED', 'INACTIVE'));
ALTER TABLE `patients` ADD CONSTRAINT `chk_patients_merged_pointer` CHECK (status <> 'MERGED' OR merged_into_patient_id IS NOT NULL);
ALTER TABLE `patients` ADD CONSTRAINT `chk_patients_not_self_merge` CHECK (merged_into_patient_id IS NULL OR merged_into_patient_id <> id);
ALTER TABLE `patients` ADD CONSTRAINT `chk_patients_address_json` CHECK (address IS NULL OR JSON_VALID(address));
ALTER TABLE `patients` ADD CONSTRAINT `fk_patients_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patients` ADD CONSTRAINT `fk_patients_merged_into` FOREIGN KEY (`tenant_id`, `merged_into_patient_id`) REFERENCES `patients` (`tenant_id`, `id`);

-- Constraints for `patient_search_tokens` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_search_tokens` ADD CONSTRAINT `chk_patient_search_tokens_kind` CHECK (token_kind IN ('NAME', 'SKELETON'));
ALTER TABLE `patient_search_tokens` ADD CONSTRAINT `fk_patient_search_tokens_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_search_tokens` ADD CONSTRAINT `fk_patient_search_tokens_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);

-- Constraints for `patient_contacts` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_contacts` ADD CONSTRAINT `chk_patient_contacts_type` CHECK (type IN ('PHONE', 'EMAIL', 'WHATSAPP'));
ALTER TABLE `patient_contacts` ADD CONSTRAINT `chk_patient_contacts_verification` CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED'));
ALTER TABLE `patient_contacts` ADD CONSTRAINT `chk_patient_contacts_status` CHECK (status IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE `patient_contacts` ADD CONSTRAINT `chk_patient_contacts_relationship` CHECK (relationship IN ('SELF', 'CAREGIVER', 'EMERGENCY'));
ALTER TABLE `patient_contacts` ADD CONSTRAINT `fk_patient_contacts_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_contacts` ADD CONSTRAINT `fk_patient_contacts_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_contacts` ADD COLUMN `active_contact_key` VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status = 'ACTIVE', CONCAT(patient_id, ':', type, ':', normalized_value_hash), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_patient_contacts_active` ON `patient_contacts` (`tenant_id`, `active_contact_key`);

-- Constraints for `patient_identifiers` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_identifiers` ADD CONSTRAINT `chk_patient_identifiers_type` CHECK (identifier_type IN ('NID', 'BIRTH_REGISTRATION', 'PASSPORT', 'OTHER'));
ALTER TABLE `patient_identifiers` ADD CONSTRAINT `chk_patient_identifiers_source` CHECK (source IN ('STAFF', 'PATIENT', 'IMPORT'));
ALTER TABLE `patient_identifiers` ADD CONSTRAINT `chk_patient_identifiers_verification` CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED'));
ALTER TABLE `patient_identifiers` ADD CONSTRAINT `fk_patient_identifiers_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_identifiers` ADD CONSTRAINT `fk_patient_identifiers_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_identifiers` ADD COLUMN `verified_identifier_key` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin AS (IF(verification_status = 'VERIFIED', CONCAT(identifier_type, ':', identifier_value_hash), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_patient_identifiers_verified` ON `patient_identifiers` (`tenant_id`, `verified_identifier_key`);

-- Constraints for `patient_consents` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_consents` ADD CONSTRAINT `chk_patient_consents_purpose` CHECK (purpose IN ('care', 'in_app', 'sms', 'whatsapp', 'email', 'telemedicine', 'ai_assistance', 'research'));
ALTER TABLE `patient_consents` ADD CONSTRAINT `chk_patient_consents_status` CHECK (status IN ('GRANTED', 'WITHDRAWN'));
ALTER TABLE `patient_consents` ADD CONSTRAINT `chk_patient_consents_given_by` CHECK (given_by_relationship IN ('SELF', 'GUARDIAN', 'STAFF_RECORDED'));
ALTER TABLE `patient_consents` ADD CONSTRAINT `chk_patient_consents_withdrawn` CHECK (status <> 'WITHDRAWN' OR withdrawn_at IS NOT NULL);
ALTER TABLE `patient_consents` ADD CONSTRAINT `fk_patient_consents_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_consents` ADD CONSTRAINT `fk_patient_consents_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);

-- Constraints for `patient_merge_cases` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_merge_cases` ADD CONSTRAINT `chk_patient_merge_cases_status` CHECK (status IN ('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REVERSED'));
ALTER TABLE `patient_merge_cases` ADD CONSTRAINT `chk_patient_merge_cases_distinct` CHECK (source_patient_id <> target_patient_id);
ALTER TABLE `patient_merge_cases` ADD CONSTRAINT `fk_patient_merge_cases_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_merge_cases` ADD CONSTRAINT `fk_patient_merge_cases_source` FOREIGN KEY (`tenant_id`, `source_patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_merge_cases` ADD CONSTRAINT `fk_patient_merge_cases_target` FOREIGN KEY (`tenant_id`, `target_patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_merge_cases` ADD COLUMN `open_source_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('OPEN', 'IN_REVIEW'), source_patient_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_merge_open_source` ON `patient_merge_cases` (`tenant_id`, `open_source_key`);

-- Constraints for `patient_accounts` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_accounts` ADD CONSTRAINT `chk_patient_accounts_relationship` CHECK (relationship IN ('SELF'));
ALTER TABLE `patient_accounts` ADD CONSTRAINT `chk_patient_accounts_method` CHECK (verification_method IN ('OTP_PHONE_MATCH', 'STAFF_VERIFIED_IN_PERSON', 'STAFF_VERIFIED_DOCUMENT'));
ALTER TABLE `patient_accounts` ADD CONSTRAINT `chk_patient_accounts_status` CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED'));
ALTER TABLE `patient_accounts` ADD CONSTRAINT `fk_patient_accounts_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_accounts` ADD CONSTRAINT `fk_patient_accounts_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `patient_accounts` ADD CONSTRAINT `fk_patient_accounts_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_accounts` ADD COLUMN `live_account_key` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('PENDING', 'ACTIVE'), CONCAT(user_id, ':', patient_id), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_patient_accounts_live` ON `patient_accounts` (`tenant_id`, `live_account_key`);

-- Constraints for `patient_guardianships` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_relationship` CHECK (relationship IN ('PARENT', 'LEGAL_GUARDIAN', 'SPOUSE', 'CHILD', 'OTHER_CAREGIVER'));
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_method` CHECK (verification_method IS NULL OR verification_method IN ('STAFF_VERIFIED_IN_PERSON', 'STAFF_VERIFIED_DOCUMENT'));
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_status` CHECK (status IN ('PENDING', 'ACTIVE', 'ENDED', 'REVOKED'));
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_window` CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_distinct` CHECK (guardian_patient_id IS NULL OR guardian_patient_id <> dependent_patient_id);
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `chk_patient_guardianships_scope_json` CHECK (JSON_VALID(authority_scope));
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `fk_patient_guardianships_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `fk_patient_guardianships_user` FOREIGN KEY (`guardian_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `fk_patient_guardianships_guardian` FOREIGN KEY (`tenant_id`, `guardian_patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_guardianships` ADD CONSTRAINT `fk_patient_guardianships_dependent` FOREIGN KEY (`tenant_id`, `dependent_patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_guardianships` ADD COLUMN `live_guardianship_key` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('PENDING', 'ACTIVE'), CONCAT(guardian_user_id, ':', dependent_patient_id), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_guardianships_live` ON `patient_guardianships` (`tenant_id`, `live_guardianship_key`);

-- Constraints for `care_team_members` (DATABASE-IMPLEMENTATION.md §3.4). Appended by db:migration:normalize.
ALTER TABLE `care_team_members` ADD CONSTRAINT `chk_care_team_members_role` CHECK (role IN ('DOCTOR', 'NURSE', 'OTHER'));
ALTER TABLE `care_team_members` ADD CONSTRAINT `chk_care_team_members_window` CHECK (ends_at IS NULL OR ends_at > starts_at);
ALTER TABLE `care_team_members` ADD CONSTRAINT `fk_care_team_members_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `care_team_members` ADD CONSTRAINT `fk_care_team_members_user` FOREIGN KEY (`member_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `care_team_members` ADD CONSTRAINT `fk_care_team_members_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `care_team_members` ADD COLUMN `open_member_key` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin AS (IF(ends_at IS NULL, CONCAT(patient_id, ':', member_user_id, ':', role), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_care_team_open` ON `care_team_members` (`tenant_id`, `open_member_key`);
