-- hmedic:normalized v1
-- Migration 202610101457_0022_telemedicine. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `telemedicine_sessions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_adapter` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_session_id` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `issued_at` DATETIME(3) NOT NULL,
    `expires_at` DATETIME(3) NOT NULL,
    `ended_at` DATETIME(3) NULL,
    `ended_reason` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `recording_policy` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DISABLED',
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_telemedicine_encounter`(`tenant_id`, `encounter_id`, `created_at`),
    INDEX `ix_telemedicine_expiry`(`status`, `expires_at`),
    UNIQUE INDEX `uq_telemedicine_sessions_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_telemedicine_provider_session`(`provider_adapter`, `provider_session_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `telemedicine_participants` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `session_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `role` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `authorization_state` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `join_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `leave_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `reconnect_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `last_joined_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_telemedicine_participants_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_telemedicine_participant_identity`(`tenant_id`, `session_id`, `participant_type`, `participant_user_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `telemedicine_participant_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `session_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `participant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_adapter` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `provider_event_id` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `kind` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `received_at` DATETIME(3) NOT NULL,
    `payload_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_telemedicine_events_session`(`tenant_id`, `session_id`, `received_at`),
    UNIQUE INDEX `uq_telemedicine_participant_event`(`provider_adapter`, `provider_event_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

CREATE UNIQUE INDEX `uq_telemedicine_participants_session_id` ON `telemedicine_participants` (`tenant_id`,`session_id`,`id`);

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
ALTER TABLE `telemedicine_sessions` ADD COLUMN `active_encounter_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('PENDING','ACTIVE'), encounter_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_telemed_active` ON `telemedicine_sessions` (`tenant_id`,`active_encounter_key`);
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `fk_telemedicine_sessions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `fk_telemedicine_sessions_encounter` FOREIGN KEY (`tenant_id`,`encounter_id`) REFERENCES `encounters` (`tenant_id`,`id`);
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_status` CHECK (status IN ('PENDING','ACTIVE','ENDED','FAILED','EXPIRED'));
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_recording` CHECK (recording_policy = 'DISABLED');
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_expiry` CHECK (expires_at > issued_at);
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_provider` CHECK (status <> 'ACTIVE' OR provider_session_id IS NOT NULL);
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_end` CHECK ((status = 'ENDED' AND ended_at IS NOT NULL AND ended_reason IS NOT NULL) OR (status <> 'ENDED' AND ended_at IS NULL AND ended_reason IS NULL));
ALTER TABLE `telemedicine_sessions` ADD CONSTRAINT `chk_telemedicine_sessions_version` CHECK (row_version > 0);

ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `fk_telemedicine_participants_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `fk_telemedicine_participants_session` FOREIGN KEY (`tenant_id`,`session_id`) REFERENCES `telemedicine_sessions` (`tenant_id`,`id`);
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `fk_telemedicine_participants_user` FOREIGN KEY (`participant_user_id`) REFERENCES `users` (`id`);
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `fk_telemedicine_participants_patient` FOREIGN KEY (`tenant_id`,`participant_patient_id`) REFERENCES `patients` (`tenant_id`,`id`);
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `chk_telemedicine_participants_type` CHECK (participant_type IN ('STAFF','PATIENT_CONTEXT'));
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `chk_telemedicine_participants_role` CHECK (role IN ('DOCTOR','STAFF','PATIENT','GUARDIAN'));
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `chk_telemedicine_participants_authorization` CHECK (authorization_state IN ('AUTHORIZED','REVOKED'));
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `chk_telemedicine_participants_identity` CHECK ((participant_type = 'STAFF' AND participant_patient_id IS NULL AND role IN ('DOCTOR','STAFF')) OR (participant_type = 'PATIENT_CONTEXT' AND participant_patient_id IS NOT NULL AND role IN ('PATIENT','GUARDIAN')));
ALTER TABLE `telemedicine_participants` ADD CONSTRAINT `chk_telemedicine_participants_version` CHECK (row_version > 0);

ALTER TABLE `telemedicine_participant_events` ADD CONSTRAINT `fk_telemedicine_events_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `telemedicine_participant_events` ADD CONSTRAINT `fk_telemedicine_events_session` FOREIGN KEY (`tenant_id`,`session_id`) REFERENCES `telemedicine_sessions` (`tenant_id`,`id`);
ALTER TABLE `telemedicine_participant_events` ADD CONSTRAINT `fk_telemedicine_events_participant` FOREIGN KEY (`tenant_id`,`session_id`,`participant_id`) REFERENCES `telemedicine_participants` (`tenant_id`,`session_id`,`id`);
ALTER TABLE `telemedicine_participant_events` ADD CONSTRAINT `chk_telemedicine_events_kind` CHECK (kind IN ('JOINED','LEFT','RECONNECTED'));
