-- hmedic:normalized v1
-- Migration 202609261423_0009_prescriptions. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `prescriptions` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `revision` INTEGER UNSIGNED NOT NULL,
    `supersedes_prescription_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `clinical_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `render_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NOT_REQUESTED',
    `reviewed_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `reviewed_at` DATETIME(3) NULL,
    `approved_by_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `approved_at` DATETIME(3) NULL,
    `attestation_version` SMALLINT NULL,
    `approved_snapshot_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `voided_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `voided_at` DATETIME(3) NULL,
    `void_reason` VARCHAR(500) NULL,
    `clinical_reviewer_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `render_template_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `last_render_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `last_rendered_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_prescriptions_patient`(`tenant_id`, `patient_id`),
    INDEX `ix_prescriptions_encounter`(`tenant_id`, `encounter_id`),
    UNIQUE INDEX `uq_prescriptions_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_prescriptions_revision`(`tenant_id`, `encounter_id`, `revision`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `prescription_items` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `prescription_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `sequence` SMALLINT NOT NULL,
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `medication_dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `catalog_snapshot` JSON NULL,
    `free_text_name` VARCHAR(200) NULL,
    `is_free_text` BOOLEAN NOT NULL DEFAULT false,
    `strength` VARCHAR(120) NULL,
    `dosage_form` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `route` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `dose` VARCHAR(80) NOT NULL,
    `frequency` VARCHAR(80) NOT NULL,
    `duration` VARCHAR(80) NOT NULL,
    `quantity` VARCHAR(40) NULL,
    `timing` VARCHAR(80) NULL,
    `instructions` VARCHAR(500) NULL,
    `instructions_bn` VARCHAR(500) NULL,
    `substitution_allowed` BOOLEAN NOT NULL DEFAULT true,

    INDEX `ix_prescription_items_prescription`(`tenant_id`, `prescription_id`),
    INDEX `ix_prescription_items_medication`(`medication_id`),
    UNIQUE INDEX `uq_prescription_items_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_prescription_items_sequence`(`tenant_id`, `prescription_id`, `sequence`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `prescriptions` (DATABASE-IMPLEMENTATION.md §3.9, PRESCRIPTION-IMPLEMENTATION.md §1).
-- One row per revision of an encounter's prescription.
ALTER TABLE `prescriptions` ADD CONSTRAINT `chk_prescriptions_clinical_status` CHECK (clinical_status IN ('DRAFT', 'REVIEWED', 'APPROVED', 'VOID'));
ALTER TABLE `prescriptions` ADD CONSTRAINT `chk_prescriptions_render_status` CHECK (render_status IN ('NOT_REQUESTED', 'QUEUED', 'RENDERING', 'AVAILABLE', 'FAILED'));
-- An approved prescription without an approver, a time and a snapshot hash is not approved by anything.
-- The hash is what makes "this is what was approved" checkable rather than asserted.
ALTER TABLE `prescriptions` ADD CONSTRAINT `chk_prescriptions_approved_complete` CHECK (clinical_status <> 'APPROVED' OR (approved_by_doctor_profile_id IS NOT NULL AND approved_at IS NOT NULL AND approved_snapshot_sha256 IS NOT NULL));
-- Withdrawing a prescription is a clinical act, and a clinical act without a reason is unreviewable.
ALTER TABLE `prescriptions` ADD CONSTRAINT `chk_prescriptions_void_reason` CHECK (clinical_status <> 'VOID' OR void_reason IS NOT NULL);
-- Nothing renders before it is final. A draft PDF is a document that can be handed to a patient and then
-- changed, which is the one thing a prescription must never be.
ALTER TABLE `prescriptions` ADD CONSTRAINT `chk_prescriptions_render_requires_final` CHECK (render_status = 'NOT_REQUESTED' OR clinical_status IN ('APPROVED', 'VOID'));
ALTER TABLE `prescriptions` ADD CONSTRAINT `fk_prescriptions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `prescriptions` ADD CONSTRAINT `fk_prescriptions_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `prescriptions` ADD CONSTRAINT `fk_prescriptions_encounter` FOREIGN KEY (`tenant_id`, `encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
ALTER TABLE `prescriptions` ADD CONSTRAINT `fk_prescriptions_doctor` FOREIGN KEY (`tenant_id`, `doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `prescriptions` ADD CONSTRAINT `fk_prescriptions_supersedes` FOREIGN KEY (`tenant_id`, `supersedes_prescription_id`) REFERENCES `prescriptions` (`tenant_id`, `id`);
-- Exactly one approved revision per encounter, enforced by the database rather than by the service.
-- The correction flow voids the old revision and approves the new one in one transaction; without this
-- key, two concurrent approvals would both succeed and a patient would hold two valid prescriptions.
ALTER TABLE `prescriptions` ADD COLUMN `approved_encounter_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(clinical_status = 'APPROVED', encounter_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_prescriptions_one_approved` ON `prescriptions` (`tenant_id`, `approved_encounter_key`);
-- And one open draft, for the reason the note has one: two tabs must not each grow their own.
ALTER TABLE `prescriptions` ADD COLUMN `open_draft_encounter_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(clinical_status IN ('DRAFT', 'REVIEWED'), encounter_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_prescriptions_one_open_draft` ON `prescriptions` (`tenant_id`, `open_draft_encounter_key`);

-- Constraints for `prescription_items` (DATABASE-IMPLEMENTATION.md §3.9).
-- A line is either a catalog selection or free text. Both would mean the snapshot and the typed name
-- can disagree about what was prescribed; neither would mean the line names nothing at all.
ALTER TABLE `prescription_items` ADD CONSTRAINT `chk_prescription_items_source` CHECK ((is_free_text = 1 AND free_text_name IS NOT NULL AND medication_id IS NULL) OR (is_free_text = 0 AND medication_id IS NOT NULL AND free_text_name IS NULL));
-- A catalog line records which dataset version it was chosen from, so a later import cannot silently
-- change the meaning of an item somebody already signed.
ALTER TABLE `prescription_items` ADD CONSTRAINT `chk_prescription_items_catalog_version` CHECK (medication_id IS NULL OR medication_dataset_version IS NOT NULL);
ALTER TABLE `prescription_items` ADD CONSTRAINT `chk_prescription_items_sequence` CHECK (sequence >= 1);
ALTER TABLE `prescription_items` ADD CONSTRAINT `fk_prescription_items_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `prescription_items` ADD CONSTRAINT `fk_prescription_items_prescription` FOREIGN KEY (`tenant_id`, `prescription_id`) REFERENCES `prescriptions` (`tenant_id`, `id`);
-- No ON DELETE CASCADE: the catalog never deletes a medication, it deactivates it (ADR-020 §2). A row
-- referenced here must stay readable and renderable forever, which is exactly what this FK guarantees.
ALTER TABLE `prescription_items` ADD CONSTRAINT `fk_prescription_items_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);
