-- hmedic:normalized v1
-- Migration 202609180952_0002_identity_tenants. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `tenants` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `slug` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `practice_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'GROUP',
    `owner_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `default_locale` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'bn-BD',
    `default_timezone` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Dhaka',
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_tenants_slug`(`slug`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `email` VARCHAR(254) NULL,
    `email_normalized` VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `phone_e164` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `display_name` VARCHAR(120) NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `password_hash` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `password_changed_at` DATETIME(3) NULL,
    `email_verified_at` DATETIME(3) NULL,
    `phone_verified_at` DATETIME(3) NULL,
    `last_login_at` DATETIME(3) NULL,
    `token_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_users_email_normalized`(`email_normalized`),
    UNIQUE INDEX `uq_users_phone_e164`(`phone_e164`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `tenant_memberships` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `role` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `permissions` JSON NOT NULL,
    `clinic_ids` JSON NOT NULL,
    `chamber_ids` JSON NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `role_permissions_version` INTEGER NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_tenant_memberships_role`(`tenant_id`, `role`, `status`),
    INDEX `ix_tenant_memberships_user_status`(`user_id`, `status`),
    UNIQUE INDEX `uq_tenant_memberships_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_tenant_memberships_user`(`tenant_id`, `user_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `clinics` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `name_normalized_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `sms_display_name` VARCHAR(40) NULL,
    `address` JSON NULL,
    `timezone` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `locale` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `deleted_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_clinics_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `doctor_profiles` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `display_name` VARCHAR(120) NOT NULL,
    `display_name_bn` VARCHAR(120) NULL,
    `registration_body` VARCHAR(80) NULL,
    `registration_number` VARCHAR(40) NULL,
    `specialties` JSON NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_doctor_profiles_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_doctor_profiles_user`(`tenant_id`, `user_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `staff_profiles` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `title` VARCHAR(80) NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_staff_profiles_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_staff_profiles_user`(`tenant_id`, `user_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `doctor_coverages` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `covered_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `covering_doctor_profile_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `starts_at` DATETIME(3) NOT NULL,
    `ends_at` DATETIME(3) NOT NULL,
    `reason` VARCHAR(300) NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `granted_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_doctor_coverages_covering`(`tenant_id`, `covering_doctor_profile_id`, `status`, `starts_at`, `ends_at`),
    UNIQUE INDEX `uq_doctor_coverages_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `audit_logs` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `seq` BIGINT UNSIGNED NOT NULL,
    `chain_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `actor_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `acting_as` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `on_behalf_of_patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `action` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `resource_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `resource_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `outcome` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `request_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `correlation_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `ip_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `user_agent_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `metadata` JSON NOT NULL,
    `role_permissions_version` INTEGER NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_audit_logs_resource`(`tenant_id`, `resource_type`, `resource_id`, `occurred_at`),
    INDEX `ix_audit_logs_actor`(`tenant_id`, `actor_user_id`, `occurred_at`),
    UNIQUE INDEX `uq_audit_logs_chain_seq`(`chain_key`, `seq`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `outbox_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `event_name` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `event_version` SMALLINT NOT NULL,
    `aggregate_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `aggregate_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `payload` JSON NOT NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `correlation_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `causation_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `idempotency_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `claimed_by` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `claim_expires_at` DATETIME(3) NULL,
    `published_at` DATETIME(3) NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `last_error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,

    INDEX `ix_outbox_claim`(`status`, `occurred_at`),
    INDEX `ix_outbox_aggregate`(`aggregate_type`, `aggregate_id`, `occurred_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `idempotency_records` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `scope` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `idem_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `request_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `response_status` SMALLINT NULL,
    `response_snapshot` JSON NULL,
    `resource_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `resource_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `completed_at` DATETIME(3) NULL,
    `expires_at` DATETIME(3) NOT NULL,

    INDEX `ix_idempotency_records_expires`(`expires_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `tenants` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `tenants` ADD CONSTRAINT `chk_tenants_status` CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'));
ALTER TABLE `tenants` ADD CONSTRAINT `chk_tenants_practice_type` CHECK (practice_type IN ('SOLO', 'GROUP'));
ALTER TABLE `tenants` ADD CONSTRAINT `chk_tenants_solo_owner` CHECK (practice_type <> 'SOLO' OR owner_doctor_profile_id IS NOT NULL);

-- Constraints for `users` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `users` ADD CONSTRAINT `chk_users_status` CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'));
ALTER TABLE `users` ADD CONSTRAINT `chk_users_contact` CHECK (email_normalized IS NOT NULL OR phone_e164 IS NOT NULL);

-- Constraints for `tenant_memberships` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `tenant_memberships` ADD CONSTRAINT `chk_tenant_memberships_role` CHECK (role IN ('tenant_owner', 'clinic_admin', 'doctor', 'nurse', 'receptionist', 'billing_manager'));
ALTER TABLE `tenant_memberships` ADD CONSTRAINT `chk_tenant_memberships_status` CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED'));
ALTER TABLE `tenant_memberships` ADD CONSTRAINT `fk_tenant_memberships_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `tenant_memberships` ADD CONSTRAINT `fk_tenant_memberships_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `clinics` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `clinics` ADD CONSTRAINT `chk_clinics_status` CHECK (status IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE `clinics` ADD CONSTRAINT `fk_clinics_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `clinics` ADD COLUMN `active_name_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status = 'ACTIVE' AND deleted_at IS NULL, name_normalized_hash, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_clinics_active_name` ON `clinics` (`tenant_id`, `active_name_key`);

-- Constraints for `doctor_profiles` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `doctor_profiles` ADD CONSTRAINT `chk_doctor_profiles_status` CHECK (status IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE `doctor_profiles` ADD CONSTRAINT `fk_doctor_profiles_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `doctor_profiles` ADD CONSTRAINT `fk_doctor_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `tenants` ADD CONSTRAINT `fk_tenants_owner_doctor` FOREIGN KEY (`id`, `owner_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);

-- Constraints for `staff_profiles` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `staff_profiles` ADD CONSTRAINT `chk_staff_profiles_status` CHECK (status IN ('ACTIVE', 'INACTIVE'));
ALTER TABLE `staff_profiles` ADD CONSTRAINT `fk_staff_profiles_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `staff_profiles` ADD CONSTRAINT `fk_staff_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

-- Constraints for `doctor_coverages` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `chk_doctor_coverages_status` CHECK (status IN ('ACTIVE', 'REVOKED'));
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `chk_doctor_coverages_window` CHECK (ends_at > starts_at);
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `chk_doctor_coverages_distinct_doctors` CHECK (covered_doctor_profile_id <> covering_doctor_profile_id);
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `fk_doctor_coverages_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `fk_doctor_coverages_covered` FOREIGN KEY (`tenant_id`, `covered_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);
ALTER TABLE `doctor_coverages` ADD CONSTRAINT `fk_doctor_coverages_covering` FOREIGN KEY (`tenant_id`, `covering_doctor_profile_id`) REFERENCES `doctor_profiles` (`tenant_id`, `id`);

-- Constraints for `audit_logs` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `audit_logs` ADD CONSTRAINT `chk_audit_logs_actor_type` CHECK (actor_type IN ('USER', 'SYSTEM', 'PATIENT_CONTEXT', 'OPERATOR'));
ALTER TABLE `audit_logs` ADD CONSTRAINT `chk_audit_logs_acting_as` CHECK (acting_as IS NULL OR acting_as IN ('SELF', 'GUARDIAN'));
ALTER TABLE `audit_logs` ADD CONSTRAINT `chk_audit_logs_outcome` CHECK (outcome IN ('SUCCESS', 'DENIED', 'FAILED'));

-- Constraints for `outbox_events` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `outbox_events` ADD CONSTRAINT `chk_outbox_events_status` CHECK (status IN ('PENDING', 'CLAIMED', 'PUBLISHED', 'FAILED'));

-- Constraints for `idempotency_records` (DATABASE-IMPLEMENTATION.md). Appended by db:migration:normalize.
ALTER TABLE `idempotency_records` ADD CONSTRAINT `chk_idempotency_records_status` CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED_RETRYABLE'));
ALTER TABLE `idempotency_records` ADD COLUMN `tenant_scope` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IFNULL(tenant_id, 'platform')) PERSISTENT;
CREATE UNIQUE INDEX `uq_idem` ON `idempotency_records` (`tenant_scope`, `scope`, `idem_key`);
