// Migration normalizer (DATABASE-IMPLEMENTATION.md §1.3). Post-processes Prisma-generated SQL:
// - InnoDB + utf8mb4 / utf8mb4_unicode_520_ci on every table;
// - ascii_bin on `/// @ascii` columns (ids, codes, keys, hashes);
// - appends generated columns, table-level CHECKs and composite FKs from sql/constraints/<table>.sql
//   for every table created by the migration.
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

export const NORMALIZED_MARKER = '-- hmedic:normalized v1';
const ASCII = 'CHARACTER SET ascii COLLATE ascii_bin';

export function createdTables(sql) {
  return [...sql.matchAll(/CREATE TABLE `([a-z0-9_]+)`/g)].map((m) => m[1]);
}

function asciiColumns(sql, ascii) {
  // Column definitions inside CREATE TABLE blocks.
  let out = sql.replace(
    /CREATE TABLE `([a-z0-9_]+)` \(([\s\S]*?)\n\)([^;]*);/g,
    (block, table, body, tail) => {
      const cols = ascii.get(table) ?? new Set();
      const newBody = body.replace(/^(\s+`([a-z0-9_]+)` VARCHAR\(\d+\))( |,)/gm, (line, head, col, after) =>
        cols.has(col) ? `${head} ${ASCII}${after}` : line,
      );
      const newTail = tail.replace(
        /DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci/,
        'ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci',
      );
      return `CREATE TABLE \`${table}\` (${newBody}\n)${newTail};`;
    },
  );
  // ALTER TABLE ... ADD COLUMN in later migrations.
  out = out.replace(
    /ALTER TABLE `([a-z0-9_]+)` ADD COLUMN `([a-z0-9_]+)` (VARCHAR\(\d+\))/g,
    (m, table, col, type) =>
      (ascii.get(table) ?? new Set()).has(col)
        ? `ALTER TABLE \`${table}\` ADD COLUMN \`${col}\` ${type} ${ASCII}`
        : m,
  );
  return out;
}

export function normalizeMigration({ sql, name, ascii, constraintsDir }) {
  if (sql.includes(NORMALIZED_MARKER)) throw new Error(`${name}: already normalized`);
  let out = asciiColumns(sql, ascii);
  const tables = createdTables(sql);
  const constraintBlocks = [];
  for (const table of tables) {
    const file = path.join(constraintsDir, `${table}.sql`);
    if (existsSync(file)) constraintBlocks.push(readFileSync(file, 'utf8').trim());
  }
  const header = [
    NORMALIZED_MARKER,
    `-- Migration ${name}. Generated by prisma migrate diff, normalized by db:migration:normalize.`,
    '-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).',
    '',
  ].join('\n');
  const constraints = constraintBlocks.length
    ? `\n\n-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys\n${constraintBlocks.join('\n\n')}\n`
    : '\n';
  return header + out.trim() + constraints;
}
