-- hmedic:normalized v1
-- Migration 202609191237_0006_queue. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `serials` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_day_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `appointment_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `serial_number` INTEGER UNSIGNED NOT NULL,
    `queue_position` INTEGER UNSIGNED NULL,
    `source` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `care_mode` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `recall_count` SMALLINT NOT NULL DEFAULT 0,
    `recall_deadline_at` DATETIME(3) NULL,
    `late_arrival` BOOLEAN NOT NULL DEFAULT false,
    `duplicate_override` BOOLEAN NOT NULL DEFAULT false,
    `duplicate_override_reason` VARCHAR(300) NULL,
    `duplicate_override_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `rescheduled_from_serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `rescheduled_to_serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `booked_at` DATETIME(3) NULL,
    `confirmed_at` DATETIME(3) NULL,
    `checked_in_at` DATETIME(3) NULL,
    `waiting_at` DATETIME(3) NULL,
    `called_at` DATETIME(3) NULL,
    `consultation_started_at` DATETIME(3) NULL,
    `completed_at` DATETIME(3) NULL,
    `cancelled_at` DATETIME(3) NULL,
    `no_show_at` DATETIME(3) NULL,
    `cancel_reason` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_serials_queue`(`tenant_id`, `chamber_day_id`, `status`, `queue_position`, `serial_number`),
    INDEX `ix_serials_patient`(`tenant_id`, `patient_id`, `created_at`),
    UNIQUE INDEX `uq_serials_tenant_id`(`tenant_id`, `id`),
    UNIQUE INDEX `uq_serials_number`(`tenant_id`, `chamber_day_id`, `serial_number`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `check_ins` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `method` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `remote_ready` BOOLEAN NOT NULL DEFAULT false,
    `remote_ready_at` DATETIME(3) NULL,
    `checked_in_at` DATETIME(3) NOT NULL,
    `verified_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `device_meta` JSON NULL,
    `revoked_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER UNSIGNED NOT NULL DEFAULT 1,

    INDEX `ix_check_ins_serial`(`tenant_id`, `serial_id`),
    UNIQUE INDEX `uq_check_ins_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `queue_events` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `chamber_day_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `serial_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `seq` INTEGER UNSIGNED NOT NULL,
    `event_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `from_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `to_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `position_before` INTEGER NULL,
    `position_after` INTEGER NULL,
    `details` JSON NOT NULL,
    `reason` VARCHAR(300) NULL,
    `actor_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `actor_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `idempotency_key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `occurred_at` DATETIME(3) NOT NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_queue_events_serial`(`tenant_id`, `serial_id`, `occurred_at`),
    UNIQUE INDEX `uq_queue_events_day_seq`(`tenant_id`, `chamber_day_id`, `seq`),
    UNIQUE INDEX `uq_queue_events_idempotency`(`tenant_id`, `idempotency_key`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `serials` (DATABASE-IMPLEMENTATION.md §3.6). Appended by db:migration:normalize.
ALTER TABLE `serials` ADD CONSTRAINT `chk_serials_source` CHECK (source IN ('ADVANCE_BOOKING', 'WALK_IN', 'FOLLOW_UP', 'RESCHEDULE'));
ALTER TABLE `serials` ADD CONSTRAINT `chk_serials_care_mode` CHECK (care_mode IN ('PHYSICAL', 'REMOTE', 'HYBRID'));
ALTER TABLE `serials` ADD CONSTRAINT `chk_serials_status` CHECK (status IN ('BOOKED', 'CONFIRMED', 'CHECKED_IN', 'WAITING', 'CALLED', 'IN_CONSULTATION', 'SKIPPED', 'NO_SHOW', 'CANCELLED', 'RESCHEDULED', 'COMPLETED'));
ALTER TABLE `serials` ADD CONSTRAINT `chk_serials_override_reason` CHECK (duplicate_override = 0 OR duplicate_override_reason IS NOT NULL);
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_day` FOREIGN KEY (`tenant_id`, `chamber_day_id`) REFERENCES `chamber_days` (`tenant_id`, `id`);
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_appointment` FOREIGN KEY (`tenant_id`, `appointment_id`) REFERENCES `appointments` (`tenant_id`, `id`);
ALTER TABLE `serials` ADD CONSTRAINT `fk_serials_rescheduled_from` FOREIGN KEY (`tenant_id`, `rescheduled_from_serial_id`) REFERENCES `serials` (`tenant_id`, `id`);
ALTER TABLE `serials` ADD COLUMN `active_patient_day_key` VARCHAR(73) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('BOOKED', 'CONFIRMED', 'CHECKED_IN', 'WAITING', 'CALLED', 'SKIPPED', 'IN_CONSULTATION') AND duplicate_override = 0, CONCAT(chamber_day_id, ':', patient_id), NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_serials_active_patient_day` ON `serials` (`tenant_id`, `active_patient_day_key`);

-- Constraints for `check_ins` (DATABASE-IMPLEMENTATION.md §3.6). Appended by db:migration:normalize.
ALTER TABLE `check_ins` ADD CONSTRAINT `chk_check_ins_method` CHECK (method IN ('STAFF_DESK', 'PATIENT_APP', 'REMOTE_READY', 'KIOSK'));
ALTER TABLE `check_ins` ADD CONSTRAINT `fk_check_ins_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `check_ins` ADD CONSTRAINT `fk_check_ins_serial` FOREIGN KEY (`tenant_id`, `serial_id`) REFERENCES `serials` (`tenant_id`, `id`);
ALTER TABLE `check_ins` ADD COLUMN `active_serial_key` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin AS (IF(revoked_at IS NULL, serial_id, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_check_ins_active` ON `check_ins` (`tenant_id`, `active_serial_key`);

-- Constraints for `queue_events` (DATABASE-IMPLEMENTATION.md §3.6). Appended by db:migration:normalize.
ALTER TABLE `queue_events` ADD CONSTRAINT `chk_queue_events_type` CHECK (event_type IN ('SERIAL_ISSUED', 'CONFIRMED', 'CHECKED_IN', 'REMOTE_READY', 'WAITING', 'CALLED', 'SKIPPED', 'RECALLED', 'NO_SHOW', 'CANCELLED', 'RESCHEDULED', 'CONSULTATION_STARTED', 'COMPLETED', 'QUEUE_REORDERED', 'DELAY_RECORDED', 'DAY_OPENED', 'DAY_PAUSED', 'DAY_CLOSED', 'DAY_CANCELLED', 'POLICY_CHANGED', 'DUPLICATE_OVERRIDE'));
ALTER TABLE `queue_events` ADD CONSTRAINT `chk_queue_events_actor_type` CHECK (actor_type IN ('USER', 'SYSTEM', 'PATIENT_CONTEXT'));
ALTER TABLE `queue_events` ADD CONSTRAINT `fk_queue_events_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `queue_events` ADD CONSTRAINT `fk_queue_events_day` FOREIGN KEY (`tenant_id`, `chamber_day_id`) REFERENCES `chamber_days` (`tenant_id`, `id`);
ALTER TABLE `queue_events` ADD CONSTRAINT `fk_queue_events_serial` FOREIGN KEY (`tenant_id`, `serial_id`) REFERENCES `serials` (`tenant_id`, `id`);
