-- hmedic:normalized v1
-- Migration 202609180952_0014_operations_integrity. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `integrity_chain_checkpoints` (
    `chain_key` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `last_seq` BIGINT UNSIGNED NOT NULL,
    `last_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `verified_through_seq` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `verified_at` DATETIME(3) NULL,
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`chain_key`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
