-- hmedic:normalized v1
-- Migration 202609231432_0019_medication_catalog. Generated by prisma migrate diff, normalized by db:migration:normalize.
-- Never edit after it has been applied anywhere (scripts/ci/check-applied-migrations.mjs).
-- CreateTable
CREATE TABLE `medications` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `canonical_key` VARCHAR(1024) NOT NULL,
    `canonical_key_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_record_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `first_seen_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `deactivated_in_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `brand_name` VARCHAR(200) NOT NULL,
    `brand_search_key` VARCHAR(200) NOT NULL,
    `brand_name_bn` VARCHAR(200) NULL,
    `brand_bn_search_key` VARCHAR(200) NULL,
    `generic_display` VARCHAR(500) NOT NULL,
    `generic_set_key` VARCHAR(500) NOT NULL,
    `strength_text` VARCHAR(300) NULL,
    `strength_parsed` JSON NOT NULL,
    `dosage_form` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dosage_form_raw` JSON NOT NULL,
    `route` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `manufacturer_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `manufacturer_display` VARCHAR(200) NOT NULL,
    `registration_number` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `registration_alternatives` JSON NULL,
    `dgda_match` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `review_status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `monograph_source_url` VARCHAR(500) NULL,
    `source_ids` JSON NOT NULL,
    `field_provenance` JSON NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `is_synthetic` BOOLEAN NOT NULL DEFAULT false,
    `imported_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `ix_medications_manufacturer`(`manufacturer_id`),
    UNIQUE INDEX `uq_medications_canonical`(`canonical_key_sha256`),
    UNIQUE INDEX `uq_medications_dataset_record`(`dataset_record_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_generics` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `generic_key` VARCHAR(300) NOT NULL,
    `generic_key_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` VARCHAR(300) NOT NULL,
    `name_search_key` VARCHAR(300) NOT NULL,
    `aliases` JSON NOT NULL,
    `salt_forms` JSON NOT NULL,
    `dataset_record_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,

    UNIQUE INDEX `uq_medication_generics_key`(`generic_key_sha256`),
    UNIQUE INDEX `uq_medication_generics_dataset_record`(`dataset_record_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_generic_links` (
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `generic_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `position` SMALLINT NOT NULL,

    INDEX `ix_medication_generic_links_generic`(`generic_id`),
    PRIMARY KEY (`medication_id`, `generic_id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_manufacturers` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `manufacturer_key` VARCHAR(200) NOT NULL,
    `manufacturer_key_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `aliases` JSON NOT NULL,
    `dataset_record_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,

    UNIQUE INDEX `uq_medication_manufacturers_key`(`manufacturer_key_sha256`),
    UNIQUE INDEX `uq_medication_manufacturers_dataset_record`(`dataset_record_id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_aliases` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `target_type` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `generic_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `alias` VARCHAR(200) NOT NULL,
    `alias_search_key` VARCHAR(200) NOT NULL,
    `script` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `kind` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `alias_origin` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `sources` JSON NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `alias_identity_sha256` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    INDEX `ix_medication_aliases_medication`(`medication_id`),
    INDEX `ix_medication_aliases_generic`(`generic_id`),
    UNIQUE INDEX `uq_medication_aliases_identity`(`alias_identity_sha256`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_price_observations` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_id` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_url` VARCHAR(500) NOT NULL,
    `unit_price` DECIMAL(12, 2) NULL,
    `pack_price` DECIMAL(12, 2) NULL,
    `price_label` VARCHAR(80) NULL,
    `is_official_mrp` BOOLEAN NOT NULL DEFAULT false,
    `observed_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `uq_medication_price_observations`(`medication_id`, `source_id`, `observed_at`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_usage_stats` (
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `prescribed_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `last_prescribed_at` DATETIME(3) NULL,

    PRIMARY KEY (`tenant_id`, `medication_id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_dataset_imports` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `dataset_status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `environment` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `execution_path` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `refusal_reason` VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `requested_by` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `file_checksums` JSON NOT NULL,
    `schema_hashes` JSON NOT NULL,
    `counts` JSON NOT NULL,
    `checkpoint` JSON NULL,
    `error_class` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `started_at` DATETIME(3) NULL,
    `finished_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `medication_dataset_gate_attestations` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `seq` BIGINT UNSIGNED NOT NULL,
    `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `gate_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `evidence_ref` VARCHAR(500) NOT NULL,
    `summary` VARCHAR(1000) NOT NULL,
    `recorded_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `recorded_at` DATETIME(3) NOT NULL,
    `prev_row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_hash` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,

    UNIQUE INDEX `uq_meddata_gate_attestations_seq`(`seq`),
    UNIQUE INDEX `uq_meddata_gate_attestations_gate`(`dataset_version`, `gate_code`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- CreateTable
CREATE TABLE `patient_medications` (
    `id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `tenant_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `patient_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `medication_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `free_text_name` VARCHAR(200) NULL,
    `dose_text` VARCHAR(200) NULL,
    `instructions` VARCHAR(500) NULL,
    `start_date` DATE NULL,
    `end_date` DATE NULL,
    `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `source_prescription_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `source_encounter_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,
    `created_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `updated_by_user_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `row_version` INTEGER NOT NULL DEFAULT 1,

    INDEX `ix_patient_medications_patient`(`tenant_id`, `patient_id`, `status`),
    INDEX `ix_patient_medications_medication`(`medication_id`),
    UNIQUE INDEX `uq_patient_medications_tenant_id`(`tenant_id`, `id`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Constraints (sql/constraints): CHECKs, generated columns, foreign keys
-- Constraints for `medications` (DATABASE-IMPLEMENTATION.md §3.8). Appended by db:migration:normalize.
ALTER TABLE `medications` ADD CONSTRAINT `chk_medications_dgda_match` CHECK (dgda_match IN ('MATCHED', 'NOT_FOUND', 'AMBIGUOUS', 'NOT_CHECKED'));
ALTER TABLE `medications` ADD CONSTRAINT `chk_medications_review_status` CHECK (review_status IN ('UNVERIFIED', 'SAMPLED_REVIEWED', 'VERIFIED'));
-- A row is deactivated by an import, and the import that did it is part of the record. Without this a
-- deactivated medication could not be traced to the dataset version that withdrew it.
ALTER TABLE `medications` ADD CONSTRAINT `chk_medications_deactivation` CHECK (active = 1 OR deactivated_in_version IS NOT NULL);
ALTER TABLE `medications` ADD CONSTRAINT `fk_medications_manufacturer` FOREIGN KEY (`manufacturer_id`) REFERENCES `medication_manufacturers` (`id`);
-- `canonical_key` is compared as bytes: two brands differing only in case are two brands.
ALTER TABLE `medications` MODIFY `canonical_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- Search reads these under `active`, and 191 characters is the utf8mb4 index-prefix limit.
CREATE INDEX `ix_med_brand` ON `medications` (`active`, `brand_search_key`(191));
CREATE INDEX `ix_med_brand_bn` ON `medications` (`active`, `brand_bn_search_key`(191));
CREATE INDEX `ix_med_generic` ON `medications` (`active`, `generic_set_key`(191));

-- Constraints for `medication_generics` (DATABASE-IMPLEMENTATION.md §3.8).
CREATE INDEX `ix_medication_generics_name` ON `medication_generics` (`name_search_key`(191));

-- Constraints for `medication_generic_links` (DATABASE-IMPLEMENTATION.md §3.8).
ALTER TABLE `medication_generic_links` ADD CONSTRAINT `fk_medication_generic_links_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);
ALTER TABLE `medication_generic_links` ADD CONSTRAINT `fk_medication_generic_links_generic` FOREIGN KEY (`generic_id`) REFERENCES `medication_generics` (`id`);

-- Constraints for `medication_aliases` (DATABASE-IMPLEMENTATION.md §3.8).
ALTER TABLE `medication_aliases` ADD CONSTRAINT `chk_medication_aliases_target_type` CHECK (target_type IN ('MEDICATION', 'GENERIC'));
ALTER TABLE `medication_aliases` ADD CONSTRAINT `chk_medication_aliases_script` CHECK (script IN ('latin', 'bengali'));
ALTER TABLE `medication_aliases` ADD CONSTRAINT `chk_medication_aliases_kind` CHECK (kind IN ('brand_bn', 'banglish', 'brand_variant', 'generic_variant'));
ALTER TABLE `medication_aliases` ADD CONSTRAINT `chk_medication_aliases_origin` CHECK (alias_origin IN ('source', 'generated'));
-- An alias points at exactly one thing. A row claiming both, or neither, is a bug that would surface as a
-- search result belonging to nothing.
ALTER TABLE `medication_aliases` ADD CONSTRAINT `chk_medication_aliases_target` CHECK ((target_type = 'MEDICATION' AND medication_id IS NOT NULL AND generic_id IS NULL) OR (target_type = 'GENERIC' AND generic_id IS NOT NULL AND medication_id IS NULL));
ALTER TABLE `medication_aliases` ADD CONSTRAINT `fk_medication_aliases_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);
ALTER TABLE `medication_aliases` ADD CONSTRAINT `fk_medication_aliases_generic` FOREIGN KEY (`generic_id`) REFERENCES `medication_generics` (`id`);
CREATE INDEX `ix_medication_aliases_search` ON `medication_aliases` (`active`, `alias_search_key`(191));

-- Constraints for `medication_price_observations` (DATABASE-IMPLEMENTATION.md §3.8).
-- An observation with no price is not an observation.
ALTER TABLE `medication_price_observations` ADD CONSTRAINT `chk_medication_price_observations_value` CHECK (unit_price IS NOT NULL OR pack_price IS NOT NULL);
ALTER TABLE `medication_price_observations` ADD CONSTRAINT `fk_medication_price_observations_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);

-- Constraints for `medication_usage_stats` (DATABASE-IMPLEMENTATION.md §3.8).
ALTER TABLE `medication_usage_stats` ADD CONSTRAINT `fk_medication_usage_stats_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `medication_usage_stats` ADD CONSTRAINT `fk_medication_usage_stats_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);

-- Constraints for `medication_dataset_imports` (DATABASE-IMPLEMENTATION.md §3.8).
ALTER TABLE `medication_dataset_imports` ADD CONSTRAINT `chk_medication_dataset_imports_path` CHECK (execution_path IN ('CLI', 'JOB'));
ALTER TABLE `medication_dataset_imports` ADD CONSTRAINT `chk_medication_dataset_imports_status` CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'REFUSED'));
-- A refusal says why. "REFUSED" with no reason is the shape of a gate that was skipped rather than failed.
ALTER TABLE `medication_dataset_imports` ADD CONSTRAINT `chk_medication_dataset_imports_refusal` CHECK (status <> 'REFUSED' OR refusal_reason IS NOT NULL);
-- One successful import per dataset version, and one active import at a time. Two importers writing the
-- same catalog concurrently would interleave upserts and leave a version nobody can reproduce.
ALTER TABLE `medication_dataset_imports` ADD COLUMN `succeeded_version_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status = 'SUCCEEDED', dataset_version, NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_medication_dataset_imports_succeeded` ON `medication_dataset_imports` (`succeeded_version_key`);
ALTER TABLE `medication_dataset_imports` ADD COLUMN `active_import_key` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin AS (IF(status IN ('QUEUED', 'RUNNING'), 'active', NULL)) PERSISTENT;
CREATE UNIQUE INDEX `uq_medication_dataset_imports_active` ON `medication_dataset_imports` (`active_import_key`);

-- Constraints for `medication_dataset_gate_attestations` (DATABASE-IMPLEMENTATION.md §3.8, ADR-020).
-- Append-only and hash-chained on `meddata:platform`. No code path updates or deletes a row here: an
-- attestation that someone reviewed the data is worth nothing if it can be added or edited afterwards.
ALTER TABLE `medication_dataset_gate_attestations` ADD CONSTRAINT `chk_meddata_gate_attestations_code` CHECK (gate_code IN ('LEGAL_SOURCE_REVIEW', 'CLINICAL_SAMPLE_REVIEW', 'DGDA_CROSS_REFERENCE', 'IMPORT_SAFEGUARDS_VERIFIED'));
ALTER TABLE `medication_dataset_gate_attestations` ADD CONSTRAINT `fk_meddata_gate_attestations_user` FOREIGN KEY (`recorded_by_user_id`) REFERENCES `users` (`id`);

-- Constraints for `patient_medications` (DATABASE-IMPLEMENTATION.md §3.8).
ALTER TABLE `patient_medications` ADD CONSTRAINT `chk_patient_medications_status` CHECK (status IN ('ACTIVE', 'STOPPED', 'ENTERED_IN_ERROR'));
-- A catalog entry or a name the patient gave, and at least one of them. A patient arrives with a strip of
-- tablets whose brand is in no dataset; refusing to record that would lose the most clinically important
-- thing in the room.
ALTER TABLE `patient_medications` ADD CONSTRAINT `chk_patient_medications_identity` CHECK (medication_id IS NOT NULL OR free_text_name IS NOT NULL);
ALTER TABLE `patient_medications` ADD CONSTRAINT `fk_patient_medications_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`);
ALTER TABLE `patient_medications` ADD CONSTRAINT `fk_patient_medications_patient` FOREIGN KEY (`tenant_id`, `patient_id`) REFERENCES `patients` (`tenant_id`, `id`);
ALTER TABLE `patient_medications` ADD CONSTRAINT `fk_patient_medications_medication` FOREIGN KEY (`medication_id`) REFERENCES `medications` (`id`);
ALTER TABLE `patient_medications` ADD CONSTRAINT `fk_patient_medications_encounter` FOREIGN KEY (`tenant_id`, `source_encounter_id`) REFERENCES `encounters` (`tenant_id`, `id`);
