/**
 * Enum source of truth for `code(n)` columns (DATABASE-IMPLEMENTATION.md §1.1). The engine-contract test
 * reads information_schema.CHECK_CONSTRAINTS and fails if any CHECK list differs from these values.
 */
export const DB_ENUMS = {
  'jobs.status': ['QUEUED', 'RUNNING', 'WAITING_RATE_LIMIT', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'DEAD'],
  'tenants.status': ['ACTIVE', 'SUSPENDED', 'CLOSED'],
  'tenants.practice_type': ['SOLO', 'GROUP'],
  'users.status': ['ACTIVE', 'LOCKED', 'DISABLED'],
  'tenant_memberships.role': [
    'tenant_owner',
    'clinic_admin',
    'doctor',
    'nurse',
    'receptionist',
    'billing_manager',
  ],
  'tenant_memberships.status': ['INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED'],
  'clinics.status': ['ACTIVE', 'INACTIVE'],
  'doctor_profiles.status': ['ACTIVE', 'INACTIVE'],
  'staff_profiles.status': ['ACTIVE', 'INACTIVE'],
  'doctor_coverages.status': ['ACTIVE', 'REVOKED'],
  'audit_logs.actor_type': ['USER', 'SYSTEM', 'PATIENT_CONTEXT', 'OPERATOR'],
  'audit_logs.acting_as': ['SELF', 'GUARDIAN'],
  'audit_logs.outcome': ['SUCCESS', 'DENIED', 'FAILED'],
  'outbox_events.status': ['PENDING', 'CLAIMED', 'PUBLISHED', 'FAILED'],
  'idempotency_records.status': ['IN_PROGRESS', 'COMPLETED', 'FAILED_RETRYABLE'],
  'sessions.client_type': ['WEB', 'ANDROID', 'IOS'],
  'sessions.revoke_reason': ['LOGOUT', 'LOGOUT_ALL', 'REFRESH_REUSE', 'ADMIN', 'PASSWORD_CHANGED', 'EXPIRED'],
  'otp_challenges.purpose': ['LOGIN', 'PHONE_VERIFY', 'RECOVERY'],
  'otp_challenges.channel': ['SMS', 'WHATSAPP', 'MOCK'],
  'otp_challenges.status': ['PENDING', 'VERIFIED', 'EXPIRED', 'LOCKED', 'SUPERSEDED'],
  'push_devices.platform': ['ANDROID', 'IOS', 'WEB'],
  'push_devices.app': ['DOCTOR_APP', 'PATIENT_APP', 'WEB'],
  'platform_operators.status': ['ACTIVE', 'SUSPENDED', 'REVOKED'],
  'platform_gate_decisions.gate_code': ['GATE-SMS-HTTP', 'GATE-PAY-PLATFORM-COLLECTION'],
  'platform_gate_decisions.environment': ['staging', 'production'],
  'platform_gate_decisions.decision': ['ACCEPTED', 'REVOKED'],
  'provider_credentials.owner_type': ['TENANT', 'CLINIC', 'DOCTOR'],
  'provider_credentials.provider_kind': ['SMS', 'PAYMENT'],
  'provider_credentials.environment': ['sandbox', 'live', 'na'],
  'provider_credentials.status': [
    'PENDING_VALIDATION',
    'ACTIVE',
    'UNVERIFIED_UNTIL_FIRST_PAYMENT',
    'INVALID',
    'SUSPENDED_BALANCE',
    'DISABLED',
    'REVOKED',
  ],
  'provider_credentials.sender_id_status': ['UNVERIFIED', 'VERIFIED', 'INVALID'],
  'sms_balance_snapshots.credential_scope': ['PLATFORM', 'TENANT'],
  'sms_balance_snapshots.parse_status': ['PARSED', 'UNPARSED', 'ERROR'],
  // 0004 patient_identity (Stage 5)
  'patients.sex': ['FEMALE', 'MALE', 'INTERSEX', 'UNKNOWN'],
  'patients.status': ['ACTIVE', 'MERGED', 'INACTIVE'],
  'patient_search_tokens.token_kind': ['NAME', 'SKELETON'],
  'patient_contacts.type': ['PHONE', 'EMAIL', 'WHATSAPP'],
  'patient_contacts.verification_status': ['UNVERIFIED', 'VERIFIED'],
  'patient_contacts.status': ['ACTIVE', 'INACTIVE'],
  'patient_contacts.relationship': ['SELF', 'CAREGIVER', 'EMERGENCY'],
  'patient_identifiers.identifier_type': ['NID', 'BIRTH_REGISTRATION', 'PASSPORT', 'OTHER'],
  'patient_identifiers.source': ['STAFF', 'PATIENT', 'IMPORT'],
  'patient_identifiers.verification_status': ['UNVERIFIED', 'VERIFIED'],
  'patient_consents.purpose': [
    'care',
    'in_app',
    'sms',
    'whatsapp',
    'email',
    'telemedicine',
    'ai_assistance',
    'research',
  ],
  'patient_consents.status': ['GRANTED', 'WITHDRAWN'],
  'patient_consents.given_by_relationship': ['SELF', 'GUARDIAN', 'STAFF_RECORDED'],
  'patient_merge_cases.status': ['OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REVERSED'],
  'patient_accounts.relationship': ['SELF'],
  'patient_accounts.verification_method': [
    'OTP_PHONE_MATCH',
    'STAFF_VERIFIED_IN_PERSON',
    'STAFF_VERIFIED_DOCUMENT',
  ],
  'patient_accounts.status': ['PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED'],
  'patient_guardianships.relationship': ['PARENT', 'LEGAL_GUARDIAN', 'SPOUSE', 'CHILD', 'OTHER_CAREGIVER'],
  'patient_guardianships.verification_method': ['STAFF_VERIFIED_IN_PERSON', 'STAFF_VERIFIED_DOCUMENT'],
  'patient_guardianships.status': ['PENDING', 'ACTIVE', 'ENDED', 'REVOKED'],
  'care_team_members.role': ['DOCTOR', 'NURSE', 'OTHER'],
  // 0005 scheduling (Stage 5)
  'chambers.status': ['ACTIVE', 'INACTIVE'],
  'chambers.chamber_payment_mode': ['PAY_AT_CHAMBER', 'PREPAID_REQUIRED', 'OPTIONAL_ONLINE'],
  'chambers.telemedicine_payment_mode': ['PREPAID_REQUIRED', 'OPTIONAL_ONLINE'],
  'doctor_schedule_rules.rule_type': ['WEEKLY', 'EXCEPTION_OPEN', 'EXCEPTION_CLOSED'],
  'chamber_days.status': ['SCHEDULED', 'OPEN', 'PAUSED', 'CLOSED', 'CANCELLED'],
  'appointment_slots.status': ['OPEN', 'FULL', 'CLOSED'],
  'appointments.source': ['ADVANCE_BOOKING', 'WALK_IN', 'FOLLOW_UP', 'RESCHEDULE'],
  'appointments.care_mode': ['PHYSICAL', 'REMOTE', 'HYBRID'],
  'appointments.status': [
    'REQUESTED',
    'PENDING_PAYMENT',
    'BOOKED',
    'CANCELLED',
    'RESCHEDULED',
    'FULFILLED',
    'NO_SHOW',
  ],
  'appointments.payment_requirement': ['NONE', 'OPTIONAL', 'PREPAID'],
  'appointments.payment_status': ['NOT_REQUIRED', 'PENDING', 'PAID', 'WAIVED', 'REFUNDED'],
  'appointments.booked_on_behalf': ['SELF', 'GUARDIAN', 'STAFF'],
  // 0006 queue (Stage 5)
  'serials.source': ['ADVANCE_BOOKING', 'WALK_IN', 'FOLLOW_UP', 'RESCHEDULE'],
  'serials.care_mode': ['PHYSICAL', 'REMOTE', 'HYBRID'],
  'serials.status': [
    'BOOKED',
    'CONFIRMED',
    'CHECKED_IN',
    'WAITING',
    'CALLED',
    'IN_CONSULTATION',
    'SKIPPED',
    'NO_SHOW',
    'CANCELLED',
    'RESCHEDULED',
    'COMPLETED',
  ],
  'check_ins.method': ['STAFF_DESK', 'PATIENT_APP', 'REMOTE_READY', 'KIOSK'],
  'queue_events.event_type': [
    'SERIAL_ISSUED',
    'CONFIRMED',
    'CHECKED_IN',
    'REMOTE_READY',
    'WAITING',
    'CALLED',
    'SKIPPED',
    'RECALLED',
    'NO_SHOW',
    'CANCELLED',
    'RESCHEDULED',
    'CONSULTATION_STARTED',
    'COMPLETED',
    'QUEUE_REORDERED',
    'DELAY_RECORDED',
    'DAY_OPENED',
    'DAY_PAUSED',
    'DAY_CLOSED',
    'DAY_CANCELLED',
    'POLICY_CHANGED',
    'DUPLICATE_OVERRIDE',
  ],
  'queue_events.actor_type': ['USER', 'SYSTEM', 'PATIENT_CONTEXT'],
} as const;

export type DbEnumKey = keyof typeof DB_ENUMS;
export type DbEnum<K extends DbEnumKey> = (typeof DB_ENUMS)[K][number];

export type JobStatus = DbEnum<'jobs.status'>;
export type StaffRoleCode = DbEnum<'tenant_memberships.role'>;
export type MembershipStatus = DbEnum<'tenant_memberships.status'>;
export type OtpStatus = DbEnum<'otp_challenges.status'>;
export type SessionRevokeReason = DbEnum<'sessions.revoke_reason'>;
export type ChamberDayStatus = DbEnum<'chamber_days.status'>;
export type AppointmentStatus = DbEnum<'appointments.status'>;
export type SerialStatus = DbEnum<'serials.status'>;
export type QueueEventType = DbEnum<'queue_events.event_type'>;
