import 'package:flutter/widgets.dart';

/// UI strings (bn-BD default, en-BD). Keys must match in both maps (unit test).
class HmStrings {
  const HmStrings._(this._m);

  static const Map<String, Map<String, String>> all = {
    'bn': {
      'doctorApp': 'এইচমেডিক ডাক্তার',
      'patientApp': 'এইচমেডিক',
      'loginTitle': 'লগইন',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'signIn': 'লগইন করুন',
      'loginFailed': 'লগইন হয়নি। তথ্য যাচাই করে আবার চেষ্টা করুন।',
      'phone': 'মোবাইল নম্বর',
      'invalidPhone': 'সঠিক বাংলাদেশি মোবাইল নম্বর দিন।',
      'sendCode': 'কোড পাঠান',
      'resendCode': 'নতুন কোড চান',
      'code': 'ছয় অঙ্কের কোড',
      'verify': 'যাচাই করুন',
      'hintSENT': 'কোড পাঠানো হয়েছে।',
      'hintRETRY_LATER': 'কোড পাঠানো যায়নি। একটু পরে আবার চেষ্টা করুন।',
      'hintMAY_ARRIVE': 'কোড না এলে নতুন কোড চান।',
      'home': 'হোম',
      'organizations': 'আপনার প্রতিষ্ঠান',
      'noOrganizations': 'আপনার কোনো সক্রিয় প্রতিষ্ঠান নেই।',
      'noClinics': 'এখনও কোনো ক্লিনিকের সাথে যুক্ত নন।',
      'logout': 'লগআউট',
      'language': 'English',
      'loading': 'লোড হচ্ছে…',
      'error': 'কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।',
      'offline': 'ইন্টারনেট সংযোগ নেই।',
      'selectProfile': 'প্রোফাইল বেছে নিন',
      'profile': 'প্রোফাইল',
      'switchProfile': 'প্রোফাইল বদলান',
      'refresh': 'রিফ্রেশ',
      'mrn': 'এমআরএন',
      'sex': 'লিঙ্গ',
      'birth': 'জন্মতারিখ / জন্মসাল',
      'contacts': 'যোগাযোগ',
      'verified': 'যাচাইকৃত',
      'unverified': 'যাচাই হয়নি',
      'updatedJustNow': 'এইমাত্র হালনাগাদ',
      'updatedMinutesAgo': '{n} মিনিট আগে হালনাগাদ',
      'showingSavedCopy': 'অফলাইন — সংরক্ষিত কপি দেখানো হচ্ছে',
      'actingFor': '{name}-এর হয়ে কাজ করছেন',
      'relSELF': 'নিজের',
      'relPARENT': 'অভিভাবক (মা/বাবা)',
      'relLEGAL_GUARDIAN': 'আইনি অভিভাবক',
      'relSPOUSE': 'স্বামী/স্ত্রী',
      'relCHILD': 'সন্তান',
      'relOTHER_CAREGIVER': 'সেবাদানকারী',
      'sexFEMALE': 'নারী',
      'sexMALE': 'পুরুষ',
      'sexINTERSEX': 'আন্তঃলিঙ্গ',
      'sexUNKNOWN': 'অজানা',
      'mySerial': 'আমার সিরিয়াল',
      'noSerials': 'আপনার কোনো সিরিয়াল নেই।',
      'serialNumber': 'সিরিয়াল',
      'peopleAhead': 'আপনার আগে আছেন',
      'estimatedPosition': 'আনুমানিক অবস্থান',
      'estimatedWait': 'আনুমানিক অপেক্ষা (মিনিট)',
      'estimateOnly': 'এটি আনুমানিক, নিশ্চিত সময় নয়।',
      'expectedDelay': 'আনুমানিক বিলম্ব (মিনিট)',
      'imReady': 'আমি প্রস্তুত',
      'todaysQueue': 'আজকের সিরিয়াল',
      'noQueue': 'আজ এই চেম্বারে কেউ অপেক্ষায় নেই।',
      'callNext': 'পরের জনকে ডাকুন',
      'startConsultation': 'চেম্বারে নিন',
      'completeConsultation': 'শেষ করুন',
      'consultation': 'চেম্বার',
      'chiefComplaint': 'প্রধান সমস্যা',
      'history': 'ইতিহাস',
      'examination': 'পরীক্ষা',
      'assessment': 'মূল্যায়ন',
      'plan': 'পরিকল্পনা',
      'ready': 'প্রস্তুত',
      'unsaved': 'সংরক্ষণ হয়নি',
      'saving': 'সংরক্ষণ হচ্ছে…',
      'saved': 'সংরক্ষিত',
      'saveFailed': 'সংরক্ষণ হয়নি',
      'noteConflict': 'দ্বন্দ্ব',
      'noteConflictExplain': 'এই নোট অন্য জায়গা থেকেও বদলেছে। কোনটি রাখবেন বেছে নিন — কিছুই মুছে যায়নি।',
      'keepMine': 'আমার লেখা রাখুন',
      'takeTheirs': 'সার্ভারের লেখা নিন',
      'signNote': 'সই করুন',
      'amendNote': 'সংশোধন করুন',
      'amendReason': 'সংশোধনের কারণ',
      'diagnoses': 'রোগনির্ণয়',
      'addDiagnosis': 'রোগনির্ণয় লিখুন',
      'voidDiagnosis': 'বাতিল করুন',
      'voidReason': 'বাতিলের কারণ',
      'loadFailed': 'লোড হয়নি',
      'cancel': 'বাতিল',
      'confirm': 'নিশ্চিত করুন',
      'waitingCount': 'অপেক্ষায়',
      'sBOOKED': 'বুক করা',
      'sCONFIRMED': 'নিশ্চিত',
      'sCHECKED_IN': 'পৌঁছেছেন',
      'sWAITING': 'অপেক্ষায়',
      'sCALLED': 'ডাকা হয়েছে',
      'sIN_CONSULTATION': 'চেম্বারে',
      'sCOMPLETED': 'শেষ',
      'sSKIPPED': 'বাদ',
      'sNO_SHOW': 'আসেননি',
      'sCANCELLED': 'বাতিল',
      'sRESCHEDULED': 'তারিখ বদলানো',
      'staleReload': 'তালিকা এর মধ্যে বদলে গেছে। রিফ্রেশ করে আবার দেখুন।',
      'dSCHEDULED': 'নির্ধারিত',
      'dOPEN': 'চালু',
      'dPAUSED': 'বিরতি',
      'dCLOSED': 'শেষ',
      'dCANCELLED': 'বাতিল',
    },
    'en': {
      'doctorApp': 'HMedic Doctor',
      'patientApp': 'HMedic',
      'loginTitle': 'Sign in',
      'email': 'Email',
      'password': 'Password',
      'signIn': 'Sign in',
      'loginFailed': 'Sign-in failed. Check your details and try again.',
      'phone': 'Mobile number',
      'invalidPhone': 'Enter a valid Bangladesh mobile number.',
      'sendCode': 'Send code',
      'resendCode': 'Request a new code',
      'code': '6-digit code',
      'verify': 'Verify',
      'hintSENT': 'Code sent.',
      'hintRETRY_LATER': 'We could not send the code. Please try again later.',
      'hintMAY_ARRIVE': 'If the code doesn\'t arrive, request a new one.',
      'home': 'Home',
      'organizations': 'Your organizations',
      'noOrganizations': 'You have no active organization.',
      'noClinics': 'Not linked to any clinic yet.',
      'logout': 'Sign out',
      'language': 'বাংলা',
      'loading': 'Loading…',
      'error': 'Something went wrong. Please try again.',
      'offline': 'You are offline.',
      'selectProfile': 'Choose a profile',
      'profile': 'Profile',
      'switchProfile': 'Switch profile',
      'refresh': 'Refresh',
      'mrn': 'MRN',
      'sex': 'Sex',
      'birth': 'Date of birth / birth year',
      'contacts': 'Contacts',
      'verified': 'verified',
      'unverified': 'not verified',
      'updatedJustNow': 'Updated just now',
      'updatedMinutesAgo': 'Updated {n} min ago',
      'showingSavedCopy': 'Offline — showing the saved copy',
      'actingFor': 'Acting for {name}',
      'relSELF': 'Myself',
      'relPARENT': 'Parent',
      'relLEGAL_GUARDIAN': 'Legal guardian',
      'relSPOUSE': 'Spouse',
      'relCHILD': 'Child',
      'relOTHER_CAREGIVER': 'Caregiver',
      'sexFEMALE': 'Female',
      'sexMALE': 'Male',
      'sexINTERSEX': 'Intersex',
      'sexUNKNOWN': 'Unknown',
      'mySerial': 'My serial',
      'noSerials': 'You have no serials.',
      'serialNumber': 'Serial',
      'peopleAhead': 'People ahead of you',
      'estimatedPosition': 'Estimated position',
      'estimatedWait': 'Estimated wait (minutes)',
      'estimateOnly': 'This is an estimate, not a promised time.',
      'expectedDelay': 'Expected delay (minutes)',
      'imReady': 'I am ready',
      'todaysQueue': 'Today’s queue',
      'noQueue': 'Nobody is waiting in this chamber today.',
      'callNext': 'Call next',
      'startConsultation': 'Start consultation',
      'completeConsultation': 'Complete',
      'consultation': 'Consultation',
      'chiefComplaint': 'Chief complaint',
      'history': 'History',
      'examination': 'Examination',
      'assessment': 'Assessment',
      'plan': 'Plan',
      'ready': 'Ready',
      'unsaved': 'Unsaved',
      'saving': 'Saving…',
      'saved': 'Saved',
      'saveFailed': 'Not saved',
      'noteConflict': 'Conflict',
      'noteConflictExplain':
          'This note changed elsewhere too. Choose which text to keep — nothing has been lost.',
      'keepMine': 'Keep mine',
      'takeTheirs': 'Take the other version',
      'signNote': 'Sign',
      'amendNote': 'Amend',
      'amendReason': 'Reason for the correction',
      'diagnoses': 'Diagnoses',
      'addDiagnosis': 'Write a diagnosis',
      'voidDiagnosis': 'Void',
      'voidReason': 'Reason for voiding',
      'loadFailed': 'Could not load',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'waitingCount': 'Waiting',
      'sBOOKED': 'Booked',
      'sCONFIRMED': 'Confirmed',
      'sCHECKED_IN': 'Arrived',
      'sWAITING': 'Waiting',
      'sCALLED': 'Called',
      'sIN_CONSULTATION': 'In chamber',
      'sCOMPLETED': 'Done',
      'sSKIPPED': 'Skipped',
      'sNO_SHOW': 'No show',
      'sCANCELLED': 'Cancelled',
      'sRESCHEDULED': 'Rescheduled',
      'staleReload': 'The queue changed meanwhile. Refresh and try again.',
      'dSCHEDULED': 'Scheduled',
      'dOPEN': 'Open',
      'dPAUSED': 'Paused',
      'dCLOSED': 'Closed',
      'dCANCELLED': 'Cancelled',
    },
  };

  final Map<String, String> _m;

  factory HmStrings.forLocale(Locale l) => HmStrings._(all[l.languageCode] ?? all['bn']!);

  static HmStrings of(BuildContext context) => HmStrings.forLocale(Localizations.localeOf(context));

  String t(String key) => _m[key] ?? all['bn']![key] ?? key;
}
