/**
 * Canonical error codes (API-IMPLEMENTATION.md §4). Single source for the API, contracts and clients.
 * `test/unit/error-codes.test.ts` parses the doc table and fails if this map drifts from it.
 */
export const ERROR_CODES = {
  UNAUTHENTICATED: 401,
  SESSION_REVOKED: 401,
  FORBIDDEN: 403,
  CSRF_FAILED: 403,
  TENANT_CONTEXT_REQUIRED: 400,
  PATIENT_CONTEXT_REQUIRED: 400,
  RESOURCE_NOT_FOUND: 404,
  VALIDATION_FAILED: 400,
  RATE_LIMITED: 429,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  /** Informational only: replays carry `meta.replayed=true` with the original 200/201 status. */
  IDEMPOTENCY_REPLAY: 200,
  IDEMPOTENCY_IN_PROGRESS: 409,
  IDEMPOTENCY_KEY_REUSED: 422,
  STALE_VERSION: 409,
  QUEUE_STATE_CONFLICT: 409,
  QUEUE_VERSION_CONFLICT: 409,
  QUEUE_BUSY: 503,
  CONCURRENCY_RETRY_EXHAUSTED: 503,
  INVALID_TRANSITION: 409,
  DUPLICATE_ACTIVE_SERIAL: 409,
  RECALL_LIMIT_REACHED: 409,
  CHAMBER_DAY_CLOSED: 409,
  CHAMBER_DAY_HAS_ACTIVE_CONSULTATION: 409,
  CAPACITY_EXCEEDED: 409,
  DUPLICATE_PATIENT_REVIEW_REQUIRED: 409,
  PRESCRIPTION_NOT_APPROVED: 409,
  PRESCRIPTION_NOT_EDITABLE: 409,
  UPLOAD_EXPIRED: 410,
  CHECKSUM_MISMATCH: 422,
  CONTENT_TYPE_NOT_ALLOWED: 415,
  PAYLOAD_TOO_LARGE: 413,
  DOCUMENT_NOT_AVAILABLE: 409,
  DOWNLOAD_TOKEN_INVALID: 403,
  PROVIDER_UNAVAILABLE: 503,
  FEATURE_DISABLED: 409,
  AI_REVIEW_REQUIRED: 409,
  AI_DRAFT_CLOSED: 409,
  AI_CONSENT_REQUIRED: 409,
  AI_ACK_VERSION_OUTDATED: 409,
  AI_CREDENTIAL_DUPLICATE: 409,
  AI_CREDENTIAL_REVOKED: 409,
  INVALID_CREDENTIAL: 422,
  QUOTA_EXHAUSTED: 429,
  MODEL_UNAVAILABLE: 409,
  CONTENT_BLOCKED: 422,
  SCHEMA_INVALID: 502,
  TIMEOUT: 504,
  PROVIDER_ERROR: 502,
  PHI_MINIMIZATION_FAILED: 422,
  POLICY_BLOCKED: 403,
  PAYMENT_NOT_REQUIRED: 409,
  FEE_NOT_CONFIGURED: 409,
  PAYMENT_METHOD_UNAVAILABLE: 409,
  PAYMENT_ALREADY_PAID: 409,
  PAYMENT_INTENT_EXPIRED: 409,
  PAYMENT_GATEWAY_REJECTED: 502,
  PAYMENT_GATEWAY_UNAVAILABLE: 503,
  MERCHANT_CREDENTIAL_INVALID: 422,
  REFUND_NOT_ALLOWED: 409,
  SMS_CREDENTIAL_INVALID: 422,
  MEDDATA_CHECKSUM_MISMATCH: 422,
  MEDDATA_SCHEMA_UNSUPPORTED: 422,
  MEDDATA_IMPORT_IN_PROGRESS: 409,
  PLATFORM_CONTEXT_REQUIRED: 400,
  DATA_INTEGRITY_ERROR: 500,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export function httpStatusFor(code: ErrorCode): number {
  return ERROR_CODES[code];
}

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(ERROR_CODES, value);
}
